using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Reflection;

namespace AspectCore.DynamicProxy
{
    /// <summary>
    /// 基于 Source Generator 生成物的 proxy type generator。
    /// 
    /// - 支持 registry discovery（扫描已加载程序集的 <see cref="AspectCoreSourceGeneratedProxyRegistryAttribute"/>）。
    /// - 支持手动注册 registry（通过 DI 注册 <see cref="ISourceGeneratedProxyRegistry"/>）。
    /// - 支持引擎选择与回退策略（<see cref="ProxyEngineOptions"/>）。
    /// </summary>
    [NonAspect]
    public sealed class SourceGeneratedProxyTypeGenerator : IProxyTypeGenerator
    {
        private readonly ProxyEngineOptions _options;
        private readonly IAspectValidatorBuilder _aspectValidatorBuilder;
        private readonly IReadOnlyList<ISourceGeneratedProxyRegistry> _manualRegistries;

        private volatile IProxyTypeGenerator _dynamicProxy;

        private volatile bool _scanned;
        private readonly object _scanLock = new object();
        private IReadOnlyList<ISourceGeneratedProxyRegistry> _scannedRegistries = Array.Empty<ISourceGeneratedProxyRegistry>();

        private readonly ConcurrentDictionary<CacheKey, Type> _cache = new ConcurrentDictionary<CacheKey, Type>();

        public SourceGeneratedProxyTypeGenerator(
            IAspectValidatorBuilder aspectValidatorBuilder,
            ProxyEngineOptions options,
            IEnumerable<ISourceGeneratedProxyRegistry> registries)
        {
            _aspectValidatorBuilder = aspectValidatorBuilder ?? throw new ArgumentNullException(nameof(aspectValidatorBuilder));
            _options = options ?? throw new ArgumentNullException(nameof(options));
            _manualRegistries = (registries ?? Array.Empty<ISourceGeneratedProxyRegistry>()).Where(r => r != null).ToArray();
        }

        /// <summary>
        /// Lazily creates the dynamic proxy type generator.
        /// This avoids Reflection.Emit initialization in NativeAOT scenarios
        /// where the SourceGenerator engine is used exclusively.
        /// </summary>
        private IProxyTypeGenerator GetDynamicProxy()
        {
            if (_dynamicProxy != null) return _dynamicProxy;
            _dynamicProxy = new ProxyTypeGenerator(_aspectValidatorBuilder);
            return _dynamicProxy;
        }

        public Type CreateInterfaceProxyType(Type serviceType)
            => CreateInterfaceProxyTypeCore(serviceType, implementationType: null);

        public Type CreateInterfaceProxyType(Type serviceType, Type implementationType)
            => CreateInterfaceProxyTypeCore(serviceType, implementationType);

        public Type CreateClassProxyType(Type serviceType, Type implementationType)
        {
            if (serviceType == null) throw new ArgumentNullException(nameof(serviceType));
            if (implementationType == null) throw new ArgumentNullException(nameof(implementationType));

            return CreateCore(
                kind: SourceGeneratedProxyKind.Class,
                serviceType: serviceType,
                implementationType: implementationType,
                dynamicFallback: () => GetDynamicProxy().CreateClassProxyType(serviceType, implementationType));
        }

        private Type CreateInterfaceProxyTypeCore(Type serviceType, Type implementationType)
        {
            if (serviceType == null) throw new ArgumentNullException(nameof(serviceType));

            return CreateCore(
                kind: SourceGeneratedProxyKind.Interface,
                serviceType: serviceType,
                implementationType: implementationType,
                dynamicFallback: () => implementationType == null
                    ? GetDynamicProxy().CreateInterfaceProxyType(serviceType)
                    : GetDynamicProxy().CreateInterfaceProxyType(serviceType, implementationType));
        }

        private Type CreateCore(SourceGeneratedProxyKind kind, Type serviceType, Type implementationType, Func<Type> dynamicFallback)
        {
            var engine = _options.Engine;
            if (engine == ProxyEngine.DynamicProxy)
            {
                return dynamicFallback();
            }

            // Interface proxies generated by the current SG node are implementation-type agnostic.
            // The registry entry uses implementationType == null. Keep the original implementationType
            // only for diagnostics and runtime fallback; use null for lookup + caching.
            var lookupImplType = kind == SourceGeneratedProxyKind.Interface ? null : implementationType;

            var key = new CacheKey(serviceType, lookupImplType, kind);
            if (_cache.TryGetValue(key, out var cached))
            {
                return cached;
            }

            if (TryResolveFromRegistries(serviceType, lookupImplType, kind, out var proxyType))
            {
                // If the service type is a closed generic and the resolved proxy type is an open generic,
                // close it with the same type arguments.
                if (serviceType.IsGenericType && !serviceType.IsGenericTypeDefinition &&
                    proxyType.IsGenericTypeDefinition)
                {
                    proxyType = proxyType.MakeGenericType(serviceType.GetGenericArguments());
                }
                _cache[key] = proxyType;
                return proxyType;
            }

            // miss
            var allowFallback = GetAllowRuntimeFallback(engine);
            var mustFail = _options.Strict || !allowFallback || engine == ProxyEngine.SourceGenerator;
            if (mustFail)
            {
                throw CreateMissingProxyException(serviceType, implementationType, kind, engine, allowFallback);
            }

            return dynamicFallback();
        }

        private bool GetAllowRuntimeFallback(ProxyEngine engine)
        {
            if (_options.AllowRuntimeFallback.HasValue)
            {
                return _options.AllowRuntimeFallback.Value;
            }
            return engine == ProxyEngine.Auto;
        }

        private bool TryResolveFromRegistries(Type serviceType, Type implementationType, SourceGeneratedProxyKind kind, out Type proxyType)
        {
            // manual registries first
            foreach (var r in _manualRegistries)
            {
                if (r.TryGetProxyType(serviceType, implementationType, kind, out proxyType))
                {
                    return true;
                }
            }

            EnsureScannedRegistries();
            foreach (var r in _scannedRegistries)
            {
                if (r.TryGetProxyType(serviceType, implementationType, kind, out proxyType))
                {
                    return true;
                }
            }

            proxyType = null;
            return false;
        }

        [UnconditionalSuppressMessage("TrimAnalyzer", "IL2026:RequiresUnreferencedCode", Justification = "ScanRegistries gracefully handles reflection failures and falls back to manual registries.")]
        private void EnsureScannedRegistries()
        {
            if (_scanned) return;
            lock (_scanLock)
            {
                if (_scanned) return;
                _scannedRegistries = ScanRegistries();
                _scanned = true;
            }
        }

        [RequiresUnreferencedCode("Uses reflection to discover source-generated proxy registries across all loaded assemblies.")]
        private static IReadOnlyList<ISourceGeneratedProxyRegistry> ScanRegistries()
        {
            var registries = new List<ISourceGeneratedProxyRegistry>();
            Assembly[] assemblies;
            try
            {
                assemblies = AppDomain.CurrentDomain.GetAssemblies();
            }
            catch
            {
                return registries;
            }

            foreach (var asm in assemblies)
            {
                try
                {
                    var attrs = asm.GetCustomAttributes(typeof(AspectCoreSourceGeneratedProxyRegistryAttribute), inherit: false)
                        .Cast<AspectCoreSourceGeneratedProxyRegistryAttribute>();
                    foreach (var attr in attrs)
                    {
                        var t = attr.RegistryType;
                        if (t == null) continue;
                        if (!typeof(ISourceGeneratedProxyRegistry).GetTypeInfo().IsAssignableFrom(t.GetTypeInfo()))
                        {
                            continue;
                        }
                        if (t.GetTypeInfo().DeclaredConstructors.All(c => c.IsStatic || c.GetParameters().Length != 0))
                        {
                            // require parameterless ctor for scan-instantiation
                            continue;
                        }
                        if (Activator.CreateInstance(t) is ISourceGeneratedProxyRegistry registry)
                        {
                            registries.Add(registry);
                        }
                    }
                }
                catch
                {
                    // ignore assemblies that cannot be reflected (dynamic/AOT/partial load)
                }
            }

            return registries;
        }

        private InvalidOperationException CreateMissingProxyException(Type serviceType, Type implementationType, SourceGeneratedProxyKind kind, ProxyEngine engine, bool allowFallback)
        {
            var manualCount = _manualRegistries.Count;
            EnsureScannedRegistries();
            var scannedCount = _scannedRegistries.Count;

            var implText = implementationType == null ? "<null>" : implementationType.FullName;
            var msg =
                "Failed to resolve source-generated proxy type.\n" +
                $"  Engine: {engine}\n" +
                $"  Strict: {_options.Strict}\n" +
                $"  AllowRuntimeFallback: {allowFallback}\n" +
                $"  Kind: {kind}\n" +
                $"  ServiceType: {serviceType.FullName}\n" +
                $"  ImplementationType: {implText}\n" +
                $"  ManualRegistries: {manualCount}\n" +
                $"  ScannedRegistries: {scannedCount}\n" +
                "Hint: Ensure your project references AspectCore.SourceGenerator and has [AspectCoreGenerateProxy] triggers, " +
                "and ensure the generated registry is discoverable (assembly attribute) or manually registered via DI.";

            return new InvalidOperationException(msg);
        }

        private readonly struct CacheKey : IEquatable<CacheKey>
        {
            private readonly Type _serviceType;
            private readonly Type _implType;
            private readonly SourceGeneratedProxyKind _kind;

            public CacheKey(Type serviceType, Type implType, SourceGeneratedProxyKind kind)
            {
                _serviceType = serviceType;
                _implType = implType;
                _kind = kind;
            }

            public bool Equals(CacheKey other)
                => _serviceType == other._serviceType && _implType == other._implType && _kind == other._kind;

            public override bool Equals(object obj)
                => obj is CacheKey other && Equals(other);

            public override int GetHashCode()
            {
                unchecked
                {
                    var hash = _serviceType.GetHashCode();
                    hash = (hash * 397) ^ (_implType?.GetHashCode() ?? 0);
                    hash = (hash * 397) ^ (int)_kind;
                    return hash;
                }
            }
        }
    }
}
