using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AspectCore.SourceGenerator;

internal static class ProxyEmitter
{
    public static string? EmitInterfaceProxy(Compilation compilation, ProxyEntry entry, SourceProductionContext context)
    {
        if (entry.ServiceType.TypeKind != TypeKind.Interface)
        {
            return null;
        }

        // Check events on this interface and all inherited interfaces.
        var allEvents = GetAllInterfaces(entry.ServiceType).SelectMany(i => i.GetMembers().OfType<IEventSymbol>()).ToList();
        if (allEvents.Count > 0)
        {
            context.ReportDiagnostic(GeneratorDiagnostics.UnsupportedEvent(entry.ServiceType, allEvents[0]));
            return null;
        }

        // Generic methods are supported (proxy method emits generic arity + MakeGenericMethod).

        if (TryReportUnsupportedByRefLikeParams(entry.ServiceType, context))
        {
            return null;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {entry.ProxyNamespace}");
        sb.AppendLine("{");

        var ifaceName = entry.ServiceType.ToGlobalName();
        var proxyName = entry.ProxyTypeName;
        var implementationType = entry.ImplementationType;

        // stub
        // NOTE: namespace-level types cannot be private; keep this internal.
        sb.AppendLine($"    internal sealed class {proxyName}__Stub : {ifaceName}");
        sb.AppendLine("    {");
        EmitInterfaceStubMembers(sb, entry.ServiceType);
        sb.AppendLine("    }");
        sb.AppendLine();

        // proxy
        sb.AppendLine("    [global::AspectCore.DynamicProxy.NonAspect]");
        sb.AppendLine("    [global::AspectCore.DynamicProxy.Dynamically]");
        EmitAttributes(sb, entry.ServiceType, "    ");
        sb.AppendLine($"    public sealed class {proxyName} : {ifaceName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::AspectCore.DynamicProxy.IAspectActivatorFactory _activatorFactory;");
        sb.AppendLine("        private readonly global::AspectCore.DynamicProxy.IAspectContextFactory _aspectContextFactory;");
        sb.AppendLine("        private readonly global::AspectCore.DynamicProxy.IAspectBuilderFactory _aspectBuilderFactory;");
        sb.AppendLine("        private readonly global::AspectCore.Configuration.IAspectConfiguration _aspectConfiguration;");
        sb.AppendLine("        private readonly global::System.IServiceProvider _serviceProvider;");
        sb.AppendLine($"        private readonly {ifaceName} _implementation;");
        sb.AppendLine("        private global::AspectCore.DynamicProxy.IAspectValidator _validator;");
        sb.AppendLine("#pragma warning disable CS0169 // _cachedActivator is only used for async methods");
        sb.AppendLine("        private global::AspectCore.DynamicProxy.IAspectActivator _cachedActivator;");
        sb.AppendLine("#pragma warning restore CS0169");
        sb.AppendLine();

        // ctors (both required shapes)
        sb.AppendLine($"        public {proxyName}(global::AspectCore.DynamicProxy.IAspectActivatorFactory activatorFactory, global::System.IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            _activatorFactory = activatorFactory ?? throw new ArgumentNullException(nameof(activatorFactory));");
        sb.AppendLine("            _serviceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));");
        sb.AppendLine("            _aspectContextFactory = (global::AspectCore.DynamicProxy.IAspectContextFactory)serviceProvider.GetService(typeof(global::AspectCore.DynamicProxy.IAspectContextFactory));");
        sb.AppendLine("            _aspectBuilderFactory = (global::AspectCore.DynamicProxy.IAspectBuilderFactory)serviceProvider.GetService(typeof(global::AspectCore.DynamicProxy.IAspectBuilderFactory));");
        sb.AppendLine("            _aspectConfiguration = (global::AspectCore.Configuration.IAspectConfiguration)serviceProvider.GetService(typeof(global::AspectCore.Configuration.IAspectConfiguration));");
        sb.AppendLine($"            _implementation = new {proxyName}__Stub();");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public {proxyName}(global::AspectCore.DynamicProxy.IAspectActivatorFactory activatorFactory, global::System.IServiceProvider serviceProvider, {ifaceName} implementation)");
        sb.AppendLine("        {");
        sb.AppendLine("            _activatorFactory = activatorFactory ?? throw new ArgumentNullException(nameof(activatorFactory));");
        sb.AppendLine("            _serviceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));");
        sb.AppendLine("            _aspectContextFactory = (global::AspectCore.DynamicProxy.IAspectContextFactory)serviceProvider.GetService(typeof(global::AspectCore.DynamicProxy.IAspectContextFactory));");
        sb.AppendLine("            _aspectBuilderFactory = (global::AspectCore.DynamicProxy.IAspectBuilderFactory)serviceProvider.GetService(typeof(global::AspectCore.DynamicProxy.IAspectBuilderFactory));");
        sb.AppendLine("            _aspectConfiguration = (global::AspectCore.Configuration.IAspectConfiguration)serviceProvider.GetService(typeof(global::AspectCore.Configuration.IAspectConfiguration));");
        sb.AppendLine("            _implementation = implementation; // allow null (matches runtime behavior)");
        sb.AppendLine("            EnsurePropertyInjection(_implementation);");
        sb.AppendLine("        }");
        sb.AppendLine();

        EmitPropertyInjectionHelper(sb);

        EmitValidatorHelpers(sb);
        sb.AppendLine();

        EmitInterfaceProxyMembers(sb, compilation, entry.ServiceType, implementationType, proxyName, ifaceName);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string? EmitClassProxy(Compilation compilation, ProxyEntry entry, SourceProductionContext context)
    {
        if (entry.ServiceType.TypeKind != TypeKind.Class || entry.ImplementationType is null)
        {
            return null;
        }

        if (entry.ServiceType.GetMembers().OfType<IEventSymbol>().Any())
        {
            var ev = entry.ServiceType.GetMembers().OfType<IEventSymbol>().First();
            context.ReportDiagnostic(GeneratorDiagnostics.UnsupportedEvent(entry.ServiceType, ev));
            return null;
        }

        // Generic methods are supported (proxy method emits generic arity + MakeGenericMethod).
        // Generic classes are also supported: type parameters are forwarded to the proxy.

        if (TryReportUnsupportedByRefLikeParams(entry.ServiceType, context))
        {
            return null;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {entry.ProxyNamespace}");
        sb.AppendLine("{");

        var serviceName = entry.ServiceType.ToGlobalName();
        var implName = entry.ImplementationType.ToGlobalName();
        var proxyName = entry.ProxyTypeName;
        var isGeneric = entry.ServiceType.IsGenericType;
        var genericParams = isGeneric ? entry.ServiceType.TypeParameters : ImmutableArray<ITypeParameterSymbol>.Empty;
        var isRecord = RecordTypeUtils.IsRecord(entry.ServiceType);

        // Build generic type parameter string for class declaration
        var genericParamList = isGeneric
            ? "<" + string.Join(", ", genericParams.Select(EmitTypeParameterWithAttributes)) + ">"
            : string.Empty;

        sb.AppendLine("    [global::AspectCore.DynamicProxy.NonAspect]");
        sb.AppendLine("    [global::AspectCore.DynamicProxy.Dynamically]");
        EmitAttributes(sb, entry.ServiceType, "    ");
        // Equality semantics note: the source generator emits the proxy as a `record class`
        // so that the C# compiler synthesises the copy constructor and `with` support needed
        // for record proxying. A side effect is that the compiler also generates value-based
        // Equals/GetHashCode/ToString. The IL emit engine produces a plain class (reference
        // equality). See docs/record-type-support.md for the full comparison and rationale.
        sb.Append(isRecord
            ? $"    public sealed record class {proxyName}{genericParamList} : {implName}"
            : $"    public sealed class {proxyName}{genericParamList} : {implName}");

        // Emit generic constraints for class-level type parameters
        if (isGeneric)
        {
            sb.AppendLine();
            EmitTypeParameterConstraints(sb, genericParams, "        ");
        }
        else
        {
            sb.AppendLine();
        }

        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::AspectCore.DynamicProxy.IAspectActivatorFactory _activatorFactory;");
        sb.AppendLine("        private readonly global::AspectCore.DynamicProxy.IAspectContextFactory _aspectContextFactory;");
        sb.AppendLine("        private readonly global::AspectCore.DynamicProxy.IAspectBuilderFactory _aspectBuilderFactory;");
        sb.AppendLine("        private readonly global::AspectCore.Configuration.IAspectConfiguration _aspectConfiguration;");
        sb.AppendLine("        private readonly global::System.IServiceProvider _serviceProvider;");
        sb.AppendLine($"        private readonly {serviceName} _implementation;");
        sb.AppendLine("        private global::AspectCore.DynamicProxy.IAspectValidator _validator;");
        sb.AppendLine("#pragma warning disable CS0169 // _cachedActivator is only used for async methods");
        sb.AppendLine("        private global::AspectCore.DynamicProxy.IAspectActivator _cachedActivator;");
        sb.AppendLine("#pragma warning restore CS0169");
        sb.AppendLine();

        EmitClassConstructors(sb, entry.ImplementationType, proxyName, implName, genericParams, isRecord);
        sb.AppendLine();
        EmitPropertyInjectionHelper(sb);
        sb.AppendLine();
        EmitValidatorHelpers(sb);
        sb.AppendLine();

        EmitClassProxyMembers(sb, compilation, entry.ServiceType, entry.ImplementationType, proxyName, serviceName, isRecord);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitPropertyInjectionHelper(StringBuilder sb)
    {
        sb.AppendLine("        private void EnsurePropertyInjection(object instance)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (instance == null) return;");
        sb.AppendLine("            EnsurePropertyInjection(instance, instance.GetType());");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private void EnsurePropertyInjection(object instance, global::System.Type injectionType)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (instance == null || injectionType == null) return;");
        sb.AppendLine("            var injectorFactory = _serviceProvider.GetService(typeof(global::AspectCore.DependencyInjection.IPropertyInjectorFactory)) as global::AspectCore.DependencyInjection.IPropertyInjectorFactory;");
        sb.AppendLine("            if (injectorFactory != null)");
        sb.AppendLine("            {");
        sb.AppendLine("                var injector = injectorFactory.Create(injectionType);");
        sb.AppendLine("                injector.Invoke(instance);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitValidatorHelpers(StringBuilder sb)
    {
        sb.AppendLine("        private global::AspectCore.DynamicProxy.IAspectValidator GetValidator()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_validator != null) return _validator;");
        sb.AppendLine("            var accessor = _activatorFactory as global::AspectCore.DynamicProxy.IAspectConfigurationAccessor;");
        sb.AppendLine("            if (accessor == null) return null;");
        sb.AppendLine("            _validator = new global::AspectCore.DynamicProxy.AspectValidatorBuilder(accessor.AspectConfiguration).Build();");
        sb.AppendLine("            return _validator;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private bool ShouldIntercept(MethodInfo serviceMethod, MethodInfo implementationMethod)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (global::AspectCore.DynamicProxy.ReflectionUtils.IsNonAspect(serviceMethod)) return false;");
        sb.AppendLine("            var v = GetValidator();");
        sb.AppendLine("            if (v == null) return false;");
        sb.AppendLine("            return v.Validate(serviceMethod, true) || v.Validate(implementationMethod, false);");
        sb.AppendLine("        }");
    }

    private static IEnumerable<INamedTypeSymbol> GetAllInterfaces(INamedTypeSymbol iface)
    {
        yield return iface;
        foreach (var baseIface in iface.AllInterfaces)
        {
            yield return baseIface;
        }
    }

    private static void EmitInterfaceStubMembers(StringBuilder sb, INamedTypeSymbol iface)
    {
        // Collect properties from this interface and all inherited interfaces.
        var seenProperties = new HashSet<string>();
        foreach (var ifaceType in GetAllInterfaces(iface))
        {
            foreach (var prop in ifaceType.GetMembers().OfType<IPropertySymbol>())
            {
                var key = prop.IsIndexer
                    ? $"this[{string.Join(",", prop.Parameters.Select(p => p.Type.ToDisplayString()))}]"
                    : prop.Name;
                if (!seenProperties.Add(key)) continue;

                var typeName = prop.Type.ToGlobalName();
                var refPrefix = prop.RefKind switch
                {
                    RefKind.Ref => "ref ",
                    RefKind.RefReadOnly => "ref readonly ",
                    _ => ""
                };
                var isRefProp = prop.RefKind is RefKind.Ref or RefKind.RefReadOnly;
                // ref / ref readonly return stub getters cannot `return default` by ref;
                // they return a ref to a shared static default slot.
                var stubSlot = isRefProp ? $"__stubPropRef_{GetMethodId(prop.GetMethod!)}" : null;
                if (prop.IsIndexer)
                {
                    // minimal indexer stub
                    sb.Append("        public ").Append(refPrefix).Append(typeName).Append(" this[");
                    sb.Append(string.Join(", ", prop.Parameters.Select(p => EmitParameterDecl(p))));
                    sb.AppendLine("]");
                    sb.AppendLine("        {");
                    if (prop.GetMethod is not null)
                        sb.AppendLine(isRefProp ? $"            get => ref {stubSlot};" : $"            get => default({typeName});");
                    if (prop.SetMethod is not null)
                        sb.AppendLine(prop.SetMethod.IsInitOnly ? "            init { }" : "            set { }");
                    sb.AppendLine("        }");
                    if (isRefProp)
                        sb.AppendLine($"        private static {typeName} {stubSlot};");
                }
                else
                {
                    sb.Append("        public ");
                    if (prop.IsRequired) sb.Append("required ");
                    sb.Append(refPrefix).Append(typeName).Append(' ').Append(prop.Name).AppendLine();
                    sb.AppendLine("        {");
                    if (prop.GetMethod is not null)
                        sb.AppendLine(isRefProp ? $"            get => ref {stubSlot};" : $"            get => default({typeName});");
                    if (prop.SetMethod is not null)
                        sb.AppendLine(prop.SetMethod.IsInitOnly ? "            init { }" : "            set { }");
                    sb.AppendLine("        }");
                    if (isRefProp)
                        sb.AppendLine($"        private static {typeName} {stubSlot};");
                }
                sb.AppendLine();
            }
        }

        // methods: collect from this interface and all inherited interfaces.
        // Only emit stubs for abstract members. For default interface methods, omit the member so that
        // runtime dispatch can use the DIM implementation.
        var seenMethods = new HashSet<string>();
        foreach (var ifaceType in GetAllInterfaces(iface))
        {
            foreach (var method in ifaceType.GetMembers().OfType<IMethodSymbol>()
                         .Where(m => m.MethodKind == MethodKind.Ordinary)
                         .Where(m => m.IsAbstract))
            {
                // Deduplicate by method signature (name + parameter types)
                var sig = method.Name + "(" + string.Join(",", method.Parameters.Select(p => p.Type.ToDisplayString())) + ")";
                if (!seenMethods.Add(sig)) continue;

                EmitStubMethod(sb, method);
                sb.AppendLine();
            }
        }
    }

    private static void EmitStubMethod(StringBuilder sb, IMethodSymbol method)
    {
        // C# 7.0 ref / ref readonly return stub: the accessor must match the byref
        // return of the interface member, and cannot `return default` by ref. Return a
        // ref to a shared static default slot instead (the stub is only reached for
        // interface-without-target when interception falls through). Generic ref
        // returns cannot use a static field of a method type parameter, so they throw.
        var isRefReturn = method.RefKind is RefKind.Ref or RefKind.RefReadOnly;
        var refReturnUsesStaticSlot = isRefReturn && !method.IsGenericMethod;
        var stubFieldName = refReturnUsesStaticSlot ? $"__stubRef_{GetMethodId(method)}" : null;

        sb.Append("        public ");
        if (method.RefKind == RefKind.Ref) sb.Append("ref ");
        else if (method.RefKind == RefKind.RefReadOnly) sb.Append("ref readonly ");
        sb.Append(method.ReturnsVoid ? "void" : method.ReturnType.ToGlobalName());
        sb.Append(' ').Append(method.Name).Append(EmitGenericParameterList(method)).Append('(');
        sb.Append(string.Join(", ", method.Parameters.Select(p => EmitParameterDecl(p))));
        sb.AppendLine(")");
        EmitGenericConstraints(sb, method, indent: "        ");
        sb.AppendLine("        {");
        foreach (var p in method.Parameters)
        {
            if (p.RefKind == RefKind.Out)
            {
                sb.AppendLine($"            {p.Name} = default({p.Type.ToGlobalName()});");
            }
        }

        if (refReturnUsesStaticSlot)
        {
            sb.AppendLine($"            return ref {stubFieldName};");
        }
        else if (isRefReturn)
        {
            sb.AppendLine("            throw new global::System.NotSupportedException(\"Generic ref return interface stubs are not supported without a target.\");");
        }
        else if (!method.ReturnsVoid)
        {
            sb.AppendLine($"            return default({method.ReturnType.ToGlobalName()});");
        }
        sb.AppendLine("        }");
        if (refReturnUsesStaticSlot)
        {
            // Backing slot for the ref return stub.
            sb.AppendLine($"        private static {method.ReturnType.ToGlobalName()} {stubFieldName};");
        }
    }

    private static void EmitInterfaceProxyMembers(StringBuilder sb, Compilation compilation, INamedTypeSymbol iface, INamedTypeSymbol? implementationType, string proxyName, string ifaceName)
    {
        // Collect methods and properties from this interface and all inherited interfaces.
        // Track the declaring interface type for each member so we can generate correct typeof() lookups.
        var allMethods = new List<(IMethodSymbol Method, INamedTypeSymbol DeclaringInterface)>();
        var allProps = new List<(IPropertySymbol Prop, INamedTypeSymbol DeclaringInterface)>();
        var seenMethodSigs = new HashSet<string>();
        var seenPropKeys = new HashSet<string>();

        foreach (var ifaceType in GetAllInterfaces(iface))
        {
            foreach (var method in ifaceType.GetMembers().OfType<IMethodSymbol>()
                         .Where(m => m.MethodKind == MethodKind.Ordinary))
            {
                var sig = method.Name + "(" + string.Join(",", method.Parameters.Select(p => p.Type.ToDisplayString())) + ")";
                if (seenMethodSigs.Add(sig)) allMethods.Add((method, ifaceType));
            }
            foreach (var prop in ifaceType.GetMembers().OfType<IPropertySymbol>())
            {
                var key = prop.IsIndexer
                    ? $"this[{string.Join(",", prop.Parameters.Select(p => p.Type.ToDisplayString()))}]"
                    : prop.Name;
                if (seenPropKeys.Add(key)) allProps.Add((prop, ifaceType));
            }
        }

        // meta cache
        // Suppress IL2026/IL2070/IL2072/IL3050: members accessed via GetMethod are known at code-gen time.
        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"TrimAnalyzer\", \"IL2026:RequiresUnreferencedCode\", Justification = \"Members accessed via reflection are known at proxy generation time.\")]");
        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"TrimAnalyzer\", \"IL2070:UnrecognizedReflectionPattern\", Justification = \"GetMethod uses known member names.\")]");
        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"AotAnalyzer\", \"IL3050:RequiresDynamicCode\", Justification = \"Generic method MakeGenericMethod only used for known generic arities.\")]");
        sb.AppendLine("        private static class __Meta");
        sb.AppendLine("        {");

        foreach (var (m, declIface) in allMethods)
        {
            EmitMethodMeta(sb, declIface, implementationType, proxyName, m);
        }
        foreach (var (p, declIface) in allProps)
        {
            if (p.GetMethod is not null) EmitMethodMeta(sb, declIface, implementationType, proxyName, p.GetMethod);
            if (p.SetMethod is not null) EmitMethodMeta(sb, declIface, implementationType, proxyName, p.SetMethod);
        }

        sb.AppendLine("        }");
        sb.AppendLine();

        // properties
        foreach (var (prop, _) in allProps)
        {
            EmitProxyProperty(sb, iface, implementationType, proxyName, ifaceName, prop);
            sb.AppendLine();
        }

        // methods
        foreach (var (method, _) in allMethods)
        {
            EmitProxyMethod(sb, iface, implementationType, proxyName, ifaceName, method, callTargetExpr: $"_implementation.{method.Name}");
            sb.AppendLine();
        }
    }

    private static void EmitClassConstructors(StringBuilder sb, INamedTypeSymbol implType, string proxyName, string implTypeName, ImmutableArray<ITypeParameterSymbol> classGenericParams, bool isRecord)
    {
        foreach (var ctor in implType.InstanceConstructors.Where(c => c.DeclaredAccessibility is Accessibility.Public or Accessibility.Protected or Accessibility.ProtectedOrInternal or Accessibility.ProtectedAndInternal))
        {
            // Skip the record copy constructor (e.g. `Record(Record original)`). It is
            // handled separately below (the private copy constructor for `with` support).
            // Emitting a public proxy constructor for it would produce an invalid
            // constructor signature and crash the compiler.
            if (isRecord && IsRecordCopyConstructor(implType, ctor))
            {
                continue;
            }

            EmitConstructorAttributes(sb, ctor, "        ");
            sb.Append("        public ").Append(proxyName).Append("(global::AspectCore.DynamicProxy.IAspectActivatorFactory activatorFactory, global::System.IServiceProvider serviceProvider");
            if (ctor.Parameters.Length > 0)
            {
                sb.Append(", ");
                // For generic base classes, constructor parameters may reference class-level type params.
                // ToGlobalName() on a type parameter returns just the name (e.g. "T"), which matches
                // the forwarded type params on the proxy class.
                // Use EmitParameterDecl to preserve params (C# 13), ref/out/in, and
                // scoped modifiers. Pass isConstructor: true so that call-site-specific
                // attributes (e.g. [CallerArgumentExpression]) are not forwarded to the
                // proxy constructor, which only passes arguments through to base().
                sb.Append(string.Join(", ", ctor.Parameters.Select(p => EmitParameterDecl(p, isConstructor: true))));
            }
            sb.Append(')');
            sb.Append(" : base(");
            sb.Append(string.Join(", ", ctor.Parameters.Select(p => p.Name)));
            sb.AppendLine(")");
            sb.AppendLine("        {");
            sb.AppendLine("            _activatorFactory = activatorFactory ?? throw new ArgumentNullException(nameof(activatorFactory));");
            sb.AppendLine("            _serviceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));");
            sb.AppendLine("            _aspectContextFactory = (global::AspectCore.DynamicProxy.IAspectContextFactory)serviceProvider.GetService(typeof(global::AspectCore.DynamicProxy.IAspectContextFactory));");
            sb.AppendLine("            _aspectBuilderFactory = (global::AspectCore.DynamicProxy.IAspectBuilderFactory)serviceProvider.GetService(typeof(global::AspectCore.DynamicProxy.IAspectBuilderFactory));");
            sb.AppendLine("            _aspectConfiguration = (global::AspectCore.Configuration.IAspectConfiguration)serviceProvider.GetService(typeof(global::AspectCore.Configuration.IAspectConfiguration));");
            sb.AppendLine("            _implementation = this;");
            // For generic classes, typeof(ImplName<T>) is valid inside the proxy since T is in scope.
            sb.AppendLine($"            EnsurePropertyInjection(this, typeof({implTypeName}));");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        if (!isRecord)
        {
            return;
        }

        // For generic records, the copy constructor parameter type must include the
        // type arguments (e.g. `Proxy<T> original`), but the constructor name itself
        // must NOT include them (C# constructors are declared with the bare type name).
        var genericTypeArgs = classGenericParams.Length > 0
            ? "<" + string.Join(", ", classGenericParams.Select(tp => tp.Name)) + ">"
            : string.Empty;

        sb.Append("        private ").Append(proxyName).Append("(").Append(proxyName).Append(genericTypeArgs).Append(" original)");
        sb.AppendLine(" : base(original)");
        sb.AppendLine("        {");
        sb.AppendLine("            _activatorFactory = original._activatorFactory;");
        sb.AppendLine("            _serviceProvider = original._serviceProvider;");
        sb.AppendLine("            _aspectContextFactory = original._aspectContextFactory;");
        sb.AppendLine("            _aspectBuilderFactory = original._aspectBuilderFactory;");
        sb.AppendLine("            _aspectConfiguration = original._aspectConfiguration;");
        sb.AppendLine("            _implementation = this;");
        sb.AppendLine("            _validator = original._validator;");
        sb.AppendLine("            _cachedActivator = original._cachedActivator;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    /// <summary>
    /// Determines whether the given constructor is the compiler-synthesized record
    /// copy constructor (e.g. <c>Record(Record original)</c>), which must be skipped
    /// when generating proxy constructors and handled separately for <c>with</c> support.
    /// </summary>
    private static bool IsRecordCopyConstructor(INamedTypeSymbol type, IMethodSymbol constructor)
    {
        if (constructor.MethodKind != MethodKind.Constructor)
        {
            return false;
        }

        if (constructor.Parameters.Length != 1)
        {
            return false;
        }

        var paramType = constructor.Parameters[0].Type;
        return SymbolEqualityComparer.Default.Equals(paramType, type);
    }

    private static void EmitClassProxyMembers(StringBuilder sb, Compilation compilation, INamedTypeSymbol serviceType, INamedTypeSymbol implType, string proxyName, string serviceName, bool isRecord)
    {
        var methods = serviceType.GetMembers().OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary)
            .Where(IsOverridable)
            .Where(m => !RecordTypeUtils.IsRecordSynthesizedMember(serviceType, m, isRecord))
            .ToList();
        var props = serviceType.GetMembers().OfType<IPropertySymbol>()
            .Where(p => (p.GetMethod is not null && IsOverridable(p.GetMethod)) || (p.SetMethod is not null && IsOverridable(p.SetMethod)))
            .Where(p => !RecordTypeUtils.IsRecordSynthesizedMember(serviceType, p, isRecord))
            .ToList();

        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"TrimAnalyzer\", \"IL2026:RequiresUnreferencedCode\", Justification = \"Members accessed via reflection are known at proxy generation time.\")]");
        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"TrimAnalyzer\", \"IL2070:UnrecognizedReflectionPattern\", Justification = \"GetMethod uses known member names.\")]");
        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"AotAnalyzer\", \"IL3050:RequiresDynamicCode\", Justification = \"Generic method MakeGenericMethod only used for known generic arities.\")]");
        sb.AppendLine("        private static class __Meta");
        sb.AppendLine("        {");
        foreach (var m in methods)
        {
            EmitMethodMeta(sb, serviceType, implType, proxyName, m);
        }
        foreach (var p in props)
        {
            if (p.GetMethod is not null) EmitMethodMeta(sb, serviceType, implType, proxyName, p.GetMethod);
            if (p.SetMethod is not null) EmitMethodMeta(sb, serviceType, implType, proxyName, p.SetMethod);
        }
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach (var prop in props)
        {
            EmitProxyProperty(sb, serviceType, implType, proxyName, serviceName, prop, isOverride: true);
            sb.AppendLine();
        }

        foreach (var method in methods)
        {
            EmitProxyMethod(sb, serviceType, implType, proxyName, serviceName, method, callTargetExpr: $"base.{method.Name}", isOverride: true);
            sb.AppendLine();
        }
    }

    private static bool IsOverridable(IMethodSymbol method)
    {
        if (method.IsStatic) return false;
        // In Roslyn, override methods have IsVirtual=false and IsOverride=true.
        // Both virtual and override methods must be proxied for class proxies.
        if (!method.IsVirtual && !method.IsOverride) return false;
        if (method.IsSealed) return false;
        if (method.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Protected or Accessibility.ProtectedOrInternal or Accessibility.ProtectedAndInternal))
            return false;
        if (method.Name == "Finalize") return false;
        return true;
    }

    private static string GetAccessibility(Accessibility accessibility)
        => accessibility switch
        {
            Accessibility.Protected => "protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.Internal => "internal",
            _ => "public",
        };

    private static void EmitMethodMeta(StringBuilder sb, INamedTypeSymbol serviceType, INamedTypeSymbol? implementationType, string proxyTypeName, IMethodSymbol method)
    {
        var suffix = GetMethodId(method);
        var serviceMethodField = $"Service_{suffix}";
        var implMethodField = $"Impl_{suffix}";
        var proxyMethodField = $"Proxy_{suffix}";

        var serviceTypeExpr = $"typeof({serviceType.ToGlobalName()})";
        // For generic proxy types, use the type name with type parameters (T is in scope inside __Meta).
        var proxyTypeArity = serviceType.IsGenericType ? serviceType.TypeParameters.Length : 0;
        var proxyTypeAritySuffix = proxyTypeArity > 0
            ? "<" + string.Join(", ", Enumerable.Range(0, proxyTypeArity).Select(i => serviceType.TypeParameters[i].Name)) + ">"
            : string.Empty;
        var proxyTypeExpr = $"typeof(global::{Naming.GeneratedProxyNamespace}.{proxyTypeName}{proxyTypeAritySuffix})";

        if (!method.IsGenericMethod)
        {
            var paramTypesExpr = EmitParameterTypesArray(method);
            sb.AppendLine($"            internal static readonly MethodInfo {serviceMethodField} = {serviceTypeExpr}.GetMethod(\"{method.Name}\", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic, binder: null, types: {paramTypesExpr}, modifiers: null);");
        }
        else
        {
            var findName = $"FindService_{suffix}";
            sb.AppendLine($"            internal static readonly MethodInfo {serviceMethodField} = {findName}();");
            sb.AppendLine($"            private static MethodInfo {findName}()");
            sb.AppendLine("            {");
            sb.AppendLine($"                foreach (var m in {serviceTypeExpr}.GetMethods(global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic))");
            sb.AppendLine("                {");
            sb.AppendLine($"                    if (m.Name != \"{method.Name}\") continue;");
            sb.AppendLine("                    if (!m.IsGenericMethodDefinition) continue;");
            sb.AppendLine($"                    if (m.GetGenericArguments().Length != {method.TypeParameters.Length}) continue;");
            sb.AppendLine("                    var ps = m.GetParameters();");
            sb.AppendLine($"                    if (ps.Length != {method.Parameters.Length}) continue;");

            for (var i = 0; i < method.Parameters.Length; i++)
            {
                var p = method.Parameters[i];
                var wantsByRef = p.RefKind is RefKind.Ref or RefKind.Out or RefKind.In;
                var expectsGenericParam = p.Type is ITypeParameterSymbol;
                var expectedTypeExpr = expectsGenericParam ? null : $"typeof({p.Type.ToGlobalName()})";

                sb.AppendLine($"                    var p{i} = ps[{i}].ParameterType;");
                if (wantsByRef)
                {
                    sb.AppendLine($"                    if (!p{i}.IsByRef) continue;");
                    sb.AppendLine($"                    p{i} = p{i}.GetElementType();");
                }
                else
                {
                    sb.AppendLine($"                    if (p{i}.IsByRef) continue;");
                }

                if (expectsGenericParam)
                {
                    sb.AppendLine($"                    if (p{i} == null || !p{i}.IsGenericParameter) continue;");
                }
                else
                {
                    sb.AppendLine($"                    if (p{i} != {expectedTypeExpr}) continue;");
                }
            }

            sb.AppendLine("                    return m;");
            sb.AppendLine("                }");
            sb.AppendLine($"                throw new MissingMethodException({serviceTypeExpr}.FullName, \"{method.Name}\");");
            sb.AppendLine("            }");
        }

        if (implementationType is null)
        {
            // no target: use service method itself
            sb.AppendLine($"            internal static readonly MethodInfo {implMethodField} = {serviceMethodField};");
        }
        else
        {
            sb.AppendLine($"            internal static readonly MethodInfo {implMethodField} = global::AspectCore.DynamicProxy.ReflectionUtils.GetMethodBySignature(typeof({implementationType.ToGlobalName()}).GetTypeInfo(), {serviceMethodField});");
        }

        if (!method.IsGenericMethod)
        {
            var paramTypesExpr = EmitParameterTypesArray(method);
            sb.AppendLine($"            internal static readonly MethodInfo {proxyMethodField} = {proxyTypeExpr}.GetMethod(\"{method.Name}\", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic, binder: null, types: {paramTypesExpr}, modifiers: null);");
        }
        else
        {
            var findName = $"FindProxy_{suffix}";
            sb.AppendLine($"            internal static readonly MethodInfo {proxyMethodField} = {findName}();");
            sb.AppendLine($"            private static MethodInfo {findName}()");
            sb.AppendLine("            {");
            sb.AppendLine($"                foreach (var m in {proxyTypeExpr}.GetMethods(global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic))");
            sb.AppendLine("                {");
            sb.AppendLine($"                    if (m.Name != \"{method.Name}\") continue;");
            sb.AppendLine("                    if (!m.IsGenericMethodDefinition) continue;");
            sb.AppendLine($"                    if (m.GetGenericArguments().Length != {method.TypeParameters.Length}) continue;");
            sb.AppendLine("                    var ps = m.GetParameters();");
            sb.AppendLine($"                    if (ps.Length != {method.Parameters.Length}) continue;");

            for (var i = 0; i < method.Parameters.Length; i++)
            {
                var p = method.Parameters[i];
                var wantsByRef = p.RefKind is RefKind.Ref or RefKind.Out or RefKind.In;
                var expectsGenericParam = p.Type is ITypeParameterSymbol;
                var expectedTypeExpr = expectsGenericParam ? null : $"typeof({p.Type.ToGlobalName()})";

                sb.AppendLine($"                    var p{i} = ps[{i}].ParameterType;");
                if (wantsByRef)
                {
                    sb.AppendLine($"                    if (!p{i}.IsByRef) continue;");
                    sb.AppendLine($"                    p{i} = p{i}.GetElementType();");
                }
                else
                {
                    sb.AppendLine($"                    if (p{i}.IsByRef) continue;");
                }

                if (expectsGenericParam)
                {
                    sb.AppendLine($"                    if (p{i} == null || !p{i}.IsGenericParameter) continue;");
                }
                else
                {
                    sb.AppendLine($"                    if (p{i} != {expectedTypeExpr}) continue;");
                }
            }

            sb.AppendLine("                    return m;");
            sb.AppendLine("                }");
            sb.AppendLine($"                throw new MissingMethodException({proxyTypeExpr}.FullName, \"{method.Name}\");");
            sb.AppendLine("            }");
        }
        sb.AppendLine();
    }

    private static void EmitProxyProperty(StringBuilder sb, INamedTypeSymbol serviceType, INamedTypeSymbol? implementationType, string proxyTypeName, string declaredTypeName, IPropertySymbol prop, bool isOverride = false)
    {
        var propTypeName = prop.Type.ToGlobalName();
        // C# 7.0 ref / ref readonly return properties and indexers must carry the
        // by-ref modifier on the declaration, otherwise an override fails CS8148.
        var refPrefix = prop.RefKind switch
        {
            RefKind.Ref => "ref ",
            RefKind.RefReadOnly => "ref readonly ",
            _ => ""
        };

        EmitAttributes(sb, prop, "        ");
        if (prop.IsIndexer)
        {
            sb.Append("        ");
            sb.Append(GetAccessibility(prop.DeclaredAccessibility));
            sb.Append(' ');
            if (isOverride) sb.Append("override ");
            sb.Append(refPrefix).Append(propTypeName).Append(" this[");
            sb.Append(string.Join(", ", prop.Parameters.Select(p => $"{p.Type.ToGlobalName()} {p.Name}")));
            sb.AppendLine("]");
        }
        else
        {
            sb.Append("        ");
            sb.Append(GetAccessibility(prop.DeclaredAccessibility));
            sb.Append(' ');
            if (prop.IsRequired) sb.Append("required ");
            if (isOverride) sb.Append("override ");
            sb.Append(refPrefix).Append(propTypeName).Append(' ').Append(prop.Name).AppendLine();
        }

        sb.AppendLine("        {");
        if (prop.GetMethod is not null)
        {
            EmitAccessorBody(sb, serviceType, implementationType, proxyTypeName, prop.GetMethod, declaredTypeName, prop, accessorKind: "get", callExpr: prop.IsIndexer ? "base" : "base", isOverride: isOverride);
        }
        if (prop.SetMethod is not null)
        {
            EmitAccessorBody(sb, serviceType, implementationType, proxyTypeName, prop.SetMethod, declaredTypeName, prop, accessorKind: "set", callExpr: prop.IsIndexer ? "base" : "base", isOverride: isOverride);
        }
        sb.AppendLine("        }");
    }

    private static void EmitAccessorBody(StringBuilder sb, INamedTypeSymbol serviceType, INamedTypeSymbol? implementationType, string proxyTypeName, IMethodSymbol accessor, string declaredTypeName, IPropertySymbol prop, string accessorKind, string callExpr, bool isOverride)
    {
        // Use same emission as method, but inside property block.
        // We'll generate a local function body as statement block.

        var suffix = GetMethodId(accessor);
        var serviceMethodField = $"__Meta.Service_{suffix}";
        var implMethodField = $"__Meta.Impl_{suffix}";
        var proxyMethodField = $"__Meta.Proxy_{suffix}";

        if (accessorKind == "get")
        {
            sb.AppendLine("            get");
            sb.AppendLine("            {");
            EmitProxyInvokeBody(
                sb,
                accessor,
                serviceMethodField,
                implMethodField,
                proxyMethodField,
                directCall: prop.IsIndexer
                    ? $"{(isOverride ? "base" : "_implementation")}[{string.Join(", ", prop.Parameters.Select(p => p.Name))}]"
                    : $"{(isOverride ? "base" : "_implementation")}.{prop.Name}",
                resolveImplementationMethodByInstance: implementationType is null,
                interfaceStubTypeName: implementationType is null ? $"{proxyTypeName}__Stub" : null);
            sb.AppendLine("            }");
        }
        else
        {
            sb.AppendLine(accessor.IsInitOnly ? "            init" : "            set");
            sb.AppendLine("            {");
            var directCall = prop.IsIndexer
                ? $"{(isOverride ? "base" : "_implementation")}[{string.Join(", ", prop.Parameters.Select(p => p.Name))}] = value"
                : $"{(isOverride ? "base" : "_implementation")}.{prop.Name} = value";
            var useReflectionDirectCall = accessor.IsInitOnly && !isOverride;
            EmitProxyInvokeBody(
                sb,
                accessor,
                serviceMethodField,
                implMethodField,
                proxyMethodField,
                directCall: directCall,
                resolveImplementationMethodByInstance: implementationType is null,
                interfaceStubTypeName: implementationType is null ? $"{proxyTypeName}__Stub" : null,
                forceReflectiveDirectCall: useReflectionDirectCall);
            sb.AppendLine("            }");
        }
    }

    private static void EmitProxyMethod(StringBuilder sb, INamedTypeSymbol serviceType, INamedTypeSymbol? implementationType, string proxyTypeName, string declaredTypeName, IMethodSymbol method, string callTargetExpr, bool isOverride = false)
    {
        EmitAttributes(sb, method, "        ");
        sb.Append("        ");
        sb.Append(GetAccessibility(method.DeclaredAccessibility));
        sb.Append(' ');
        if (isOverride) sb.Append("override ");
        // C# 7.0 ref / ref readonly return modifiers precede the return type.
        if (method.RefKind == RefKind.Ref) sb.Append("ref ");
        else if (method.RefKind == RefKind.RefReadOnly) sb.Append("ref readonly ");
        sb.Append(method.ReturnsVoid ? "void" : method.ReturnType.ToGlobalName());
        sb.Append(' ').Append(method.Name).Append(EmitGenericParameterList(method)).Append('(');
        sb.Append(string.Join(", ", method.Parameters.Select(p => EmitParameterDecl(p))));
        sb.AppendLine(")");
        EmitGenericConstraints(sb, method, indent: "        ");
        sb.AppendLine("        {");

        var suffix = GetMethodId(method);
        EmitProxyInvokeBody(
            sb,
            method,
            serviceMethodField: $"__Meta.Service_{suffix}",
            implMethodField: $"__Meta.Impl_{suffix}",
            proxyMethodField: $"__Meta.Proxy_{suffix}",
            directCall: $"{callTargetExpr}{EmitGenericTypeArgumentList(method)}({string.Join(", ", method.Parameters.Select(EmitArgument))})",
            resolveImplementationMethodByInstance: implementationType is null,
            interfaceStubTypeName: implementationType is null ? $"{proxyTypeName}__Stub" : null);

        sb.AppendLine("        }");
    }

    private static void EmitProxyInvokeBody(
        StringBuilder sb,
        IMethodSymbol method,
        string serviceMethodField,
        string implMethodField,
        string proxyMethodField,
        string directCall,
        bool resolveImplementationMethodByInstance,
        string? interfaceStubTypeName,
        bool forceReflectiveDirectCall = false)
    {
        var argCount = method.Parameters.Length;
        sb.AppendLine($"            var __serviceMethod = {serviceMethodField};");
        sb.AppendLine($"            var __implMethod = {implMethodField};");
        sb.AppendLine($"            var __proxyMethod = {proxyMethodField};");

        if (resolveImplementationMethodByInstance)
        {
            sb.AppendLine($"            if (_implementation is not null && !(_implementation is {interfaceStubTypeName}))");
            sb.AppendLine("            {");
            sb.AppendLine("                try");
            sb.AppendLine("                {");
            sb.AppendLine("                    __implMethod = global::AspectCore.DynamicProxy.ReflectionUtils.GetMethodBySignature(_implementation.GetType().GetTypeInfo(), __serviceMethod);");
            sb.AppendLine("                }");
            sb.AppendLine("                catch");
            sb.AppendLine("                {");
            sb.AppendLine("                    // ignore and fall back to service method\n");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        if (method.IsGenericMethod)
        {
            sb.AppendLine($"            var __genericArgs = new[] {{ {string.Join(", ", method.TypeParameters.Select(tp => $"typeof({tp.Name})"))} }};");
            sb.AppendLine("            if (__serviceMethod.IsGenericMethodDefinition) __serviceMethod = __serviceMethod.MakeGenericMethod(__genericArgs);");
            sb.AppendLine("            if (__implMethod.IsGenericMethodDefinition) __implMethod = __implMethod.MakeGenericMethod(__genericArgs);");
            sb.AppendLine("            if (__proxyMethod.IsGenericMethodDefinition) __proxyMethod = __proxyMethod.MakeGenericMethod(__genericArgs);");
            sb.AppendLine();
        }
        sb.AppendLine("            if (!ShouldIntercept(__serviceMethod, __implMethod))");
        sb.AppendLine("            {");
        if (method.ReturnsVoid)
        {
            if (forceReflectiveDirectCall)
            {
                EmitArgumentsArray(sb, method, indent: "                ", variableName: "__directArgs");
                sb.AppendLine("                __implMethod.Invoke(_implementation, __directArgs);");
            }
            else
            {
                sb.AppendLine($"                {directCall};");
            }
            sb.AppendLine("                return;");
        }
        else
        {
            // ref / ref readonly returns must forward the managed reference directly
            // so the non-intercepted path keeps true ref-aliasing semantics.
            var refPrefix = method.RefKind is RefKind.Ref or RefKind.RefReadOnly ? "ref " : "";
            sb.AppendLine($"                return {refPrefix}{directCall};");
        }
        sb.AppendLine("            }");
        sb.AppendLine();
        EmitArgumentsArray(sb, method, indent: "            ", variableName: "__args");
        sb.AppendLine();
        sb.AppendLine("            var __ctx = new global::AspectCore.DynamicProxy.AspectActivatorContext(");
        sb.AppendLine("                __serviceMethod,");
        sb.AppendLine("                __implMethod,");
        sb.AppendLine("                __proxyMethod,");
        sb.AppendLine("                __serviceMethod, // predicateMethod");
        sb.AppendLine("                _implementation,");
        sb.AppendLine("                this,");
        sb.AppendLine("                __args);");
        sb.AppendLine();

        // ── Optimized inline activation ──────────────────────────────────
        // Skip _activatorFactory.Create() + AspectActivator.Invoke<T>() path.
        // Instead, directly create context, get cached builder, invoke pipeline,
        // and handle result — all inline to avoid the AspectActivator allocation.
        var rk = ReturnKind.Determine(method);
        var isAsync = rk is ReturnKindKind.Task or ReturnKindKind.TaskOfT
            or ReturnKindKind.ValueTask or ReturnKindKind.ValueTaskOfT
            or ReturnKindKind.AsyncEnumerable;

        // Emit "async" modifier for async return kinds so we can await the pipeline.
        // This requires re-emitting the method signature with async... but we already
        // emitted it above. Instead, we handle async by wrapping in a helper pattern.
        // For simplicity: sync methods get full inline activation; async methods use
        // a lightweight path that still avoids AspectActivator allocation.

        if (isAsync)
        {
            // Async path: use cached activator instance (AspectActivator is stateless, safe to reuse).
            sb.AppendLine("            var __activator = _cachedActivator ?? (_cachedActivator = _activatorFactory.Create());");
            switch (rk)
            {
                case ReturnKindKind.Task:
                    sb.AppendLine("            var __task = __activator.InvokeTask<object>(__ctx);");
                    break;
                case ReturnKindKind.TaskOfT:
                    sb.AppendLine($"            var __task = __activator.InvokeTask<{GetTaskInnerType(method.ReturnType)}>(__ctx);");
                    break;
                case ReturnKindKind.ValueTask:
                    sb.AppendLine("            var __vt = __activator.InvokeValueTask<object>(__ctx);");
                    break;
                case ReturnKindKind.ValueTaskOfT:
                    sb.AppendLine($"            var __vt = __activator.InvokeValueTask<{GetValueTaskInnerType(method.ReturnType)}>(__ctx);");
                    break;
                case ReturnKindKind.AsyncEnumerable:
                    sb.AppendLine($"            var __asyncEnumerable = __activator.InvokeAsyncEnumerable<{GetAsyncEnumerableInnerType(method.ReturnType)}>(__ctx);");
                    break;
            }
        }
        else
        {
            // Sync path: fully inline activation to avoid AspectActivator allocation.
            if (rk == ReturnKindKind.Sync)
            {
                sb.AppendLine($"            {method.ReturnType.ToGlobalName()} __ret = default;");
            }
            else if (rk == ReturnKindKind.RefSync)
            {
                // ref / ref readonly return: the value-based pipeline yields a value that
                // must be materialised into a StrongBox<T> so its field can be returned by
                // ref (the managed pointer must outlive this proxy method).
                sb.AppendLine($"            var __refBox = new global::System.Runtime.CompilerServices.StrongBox<{method.ReturnType.ToGlobalName()}>();");
            }
            sb.AppendLine("            var __context = _aspectContextFactory.CreateContext(__ctx);");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                var __builder = _aspectBuilderFactory.GetBuilder(__serviceMethod, __implMethod, __serviceMethod);");
            sb.AppendLine("                var __pipeline = __builder.Build();");
            sb.AppendLine("                var __invokeTask = __pipeline(__context);");
            sb.AppendLine("                if (__invokeTask.IsFaulted)");
            sb.AppendLine("                    global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(__invokeTask.Exception.InnerException).Throw();");
            sb.AppendLine("                if (!__invokeTask.IsCompleted)");
            sb.AppendLine("                    global::AspectCore.Utils.NoSyncContextScope.Run(__invokeTask);");
            if (rk == ReturnKindKind.Sync)
            {
                sb.AppendLine($"                __ret = ({method.ReturnType.ToGlobalName()})__context.ReturnValue;");
            }
            else if (rk == ReturnKindKind.RefSync)
            {
                sb.AppendLine($"                __refBox.Value = ({method.ReturnType.ToGlobalName()})__context.ReturnValue;");
            }
            sb.AppendLine("            }");
            sb.AppendLine("            catch (global::AspectCore.DynamicProxy.AspectInvocationException)");
            sb.AppendLine("            {");
            sb.AppendLine("                _aspectContextFactory.ReleaseContext(__context);");
            sb.AppendLine("                throw;");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (global::System.Exception __ex)");
            sb.AppendLine("            {");
            sb.AppendLine("                _aspectContextFactory.ReleaseContext(__context);");
            sb.AppendLine("                if (_aspectConfiguration != null && _aspectConfiguration.ThrowAspectException)");
            sb.AppendLine("                    throw new global::AspectCore.DynamicProxy.AspectInvocationException(__context, __ex);");
            sb.AppendLine("                throw;");
            sb.AppendLine("            }");
            sb.AppendLine("            _aspectContextFactory.ReleaseContext(__context);");
        }

        // write back ref/out
        for (var i = 0; i < argCount; i++)
        {
            var p = method.Parameters[i];
            if (p.RefKind is RefKind.Ref or RefKind.Out)
            {
                sb.AppendLine($"            {p.Name} = ({p.Type.ToGlobalName()})__args[{i}];");
            }
        }

        // return
        switch (rk)
        {
            case ReturnKindKind.Void:
                sb.AppendLine("            return;");
                break;
            case ReturnKindKind.Task:
                sb.AppendLine("            return __task; // Task<object> upcast to Task");
                break;
            case ReturnKindKind.TaskOfT:
                sb.AppendLine("            return __task;");
                break;
            case ReturnKindKind.ValueTask:
                sb.AppendLine("            return new ValueTask(__vt.AsTask());");
                break;
            case ReturnKindKind.ValueTaskOfT:
                sb.AppendLine("            return __vt;");
                break;
            case ReturnKindKind.AsyncEnumerable:
                sb.AppendLine("            return __asyncEnumerable;");
                break;
            case ReturnKindKind.Sync:
                sb.AppendLine("            return __ret;");
                break;
            case ReturnKindKind.RefSync:
                sb.AppendLine("            return ref __refBox.Value;");
                break;
        }
    }

    private static void EmitArgumentsArray(StringBuilder sb, IMethodSymbol method, string indent, string variableName)
    {
        var argCount = method.Parameters.Length;
        sb.AppendLine($"{indent}var {variableName} = new object[{argCount}];");
        for (var i = 0; i < argCount; i++)
        {
            var p = method.Parameters[i];
            if (p.RefKind == RefKind.Out)
            {
                sb.AppendLine($"{indent}{variableName}[{i}] = default({p.Type.ToGlobalName()});");
            }
            else
            {
                sb.AppendLine($"{indent}{variableName}[{i}] = {p.Name};");
            }
        }
    }

    private static string EmitParameterDecl(IParameterSymbol p, bool isConstructor = false)
    {
        // C# 11 scoped modifier (e.g. scoped ref T, scoped T).
        // Detected via the compiler-generated [ScopedRef] attribute because
        // IParameterSymbol.IsScoped is not available in Roslyn 4.10.0.
        // Must come before ref/out/in in the declaration.
        var isScoped = p.GetAttributes()
            .Any(a => a.AttributeClass?.ToDisplayString() == "System.Runtime.CompilerServices.ScopedRefAttribute");
        var scopedPrefix = isScoped ? "scoped " : "";
        var prefix = p.RefKind switch
        {
            RefKind.Ref => "ref ",
            RefKind.Out => "out ",
            RefKind.In => "in ",
            _ => ""
        };
        // C# 13 params collections (params IEnumerable<T>, params ReadOnlySpan<T>)
        // and traditional params T[] are detected via IsParams. Emit the keyword
        // so the generated proxy preserves params calling semantics.
        var paramsPrefix = p.IsParams ? "params " : "";
        // For constructor parameters, skip forwarded attributes: the proxy
        // constructor merely passes arguments through to base(), so attributes
        // like [CallerArgumentExpression] are meaningless and would trigger
        // compiler warnings. The compiler synthesises [ParamCollection] itself
        // when it sees the params keyword, so that must not be emitted either.
        var attrs = isConstructor ? "" : EmitAttributesInline(p);
        return $"{attrs}{scopedPrefix}{prefix}{paramsPrefix}{p.Type.ToGlobalName()} {p.Name}";
    }

    private static void EmitConstructorAttributes(StringBuilder sb, IMethodSymbol ctor, string indent)
    {
        foreach (var attr in ctor.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() != "System.Diagnostics.CodeAnalysis.SetsRequiredMembersAttribute")
            {
                continue;
            }

            sb.Append(indent).AppendLine("[global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]");
        }
    }

    private static bool TryReportUnsupportedByRefLikeParams(INamedTypeSymbol serviceType, SourceProductionContext context)
    {
        foreach (var method in GetProxyableMethods(serviceType).Concat(GetProxyablePropertyAccessors(serviceType)))
        {
            var parameter = method.Parameters.FirstOrDefault(p => p.IsParams && IsByRefLikeType(p.Type));
            if (parameter is null)
            {
                continue;
            }

            context.ReportDiagnostic(GeneratorDiagnostics.UnsupportedByRefLikeParams(method, parameter));
            return true;
        }

        foreach (var constructor in serviceType.InstanceConstructors.Where(c =>
                     c.DeclaredAccessibility is Accessibility.Public or Accessibility.Protected or Accessibility.ProtectedOrInternal or Accessibility.ProtectedAndInternal))
        {
            var parameter = constructor.Parameters.FirstOrDefault(p => p.IsParams && IsByRefLikeType(p.Type));
            if (parameter is null)
            {
                continue;
            }

            context.ReportDiagnostic(GeneratorDiagnostics.UnsupportedByRefLikeParams(constructor, parameter));
            return true;
        }

        return false;
    }

    private static IEnumerable<IMethodSymbol> GetProxyablePropertyAccessors(INamedTypeSymbol serviceType)
    {
        var properties = serviceType.TypeKind == TypeKind.Interface
            ? GetAllInterfaces(serviceType).SelectMany(i => i.GetMembers().OfType<IPropertySymbol>())
            : serviceType.GetMembers().OfType<IPropertySymbol>();

        return properties
            .Where(p => p.IsIndexer)
            .SelectMany(p => new[] { p.GetMethod, p.SetMethod })
            .OfType<IMethodSymbol>()
            .Where(m => serviceType.TypeKind == TypeKind.Interface || IsOverridable(m));
    }

    private static IEnumerable<IMethodSymbol> GetProxyableMethods(INamedTypeSymbol serviceType)
    {
        if (serviceType.TypeKind == TypeKind.Interface)
        {
            return GetAllInterfaces(serviceType)
                .SelectMany(i => i.GetMembers().OfType<IMethodSymbol>())
                .Where(m => m.MethodKind == MethodKind.Ordinary);
        }

        return serviceType.GetMembers().OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary)
            .Where(IsOverridable);
    }

    private static bool IsByRefLikeType(ITypeSymbol type)
    {
        return type is INamedTypeSymbol { IsRefLikeType: true };
    }

    private static string EmitArgument(IParameterSymbol p)
    {
        var prefix = p.RefKind switch
        {
            RefKind.Ref => "ref ",
            RefKind.Out => "out ",
            RefKind.In => "in ",
            _ => ""
        };
        return $"{prefix}{p.Name}";
    }

    private static string EmitParameterTypesArray(IMethodSymbol method)
    {
        if (method.Parameters.Length == 0) return "Type.EmptyTypes";

        var parts = method.Parameters.Select(p =>
        {
            var t = $"typeof({p.Type.ToGlobalName()})";
            if (p.RefKind is RefKind.Ref or RefKind.Out or RefKind.In)
            {
                t += ".MakeByRefType()";
            }
            return t;
        });

        return $"new[] {{ {string.Join(", ", parts)} }}";
    }

    private static string GetMethodId(IMethodSymbol method)
    {
        // Deterministic, collision-resistant ID using FNV-1a hash on the full method signature.
        // Combined with method name and parameter count, this is unique within a generated proxy.
        var sig = method.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        var hash = Fnv1a32(sig);
        return $"{method.Name}_{method.Parameters.Length}_{hash:X8}";
    }

    private static uint Fnv1a32(string s)
    {
        const uint fnvPrime = 16777619;
        const uint fnvOffset = 2166136261;
        uint hash = fnvOffset;
        for (int i = 0; i < s.Length; i++)
        {
            hash ^= s[i];
            hash *= fnvPrime;
        }
        return hash;
    }

    private static string GetAsyncEnumerableInnerType(ITypeSymbol asyncEnumerableType)
    {
        if (asyncEnumerableType is INamedTypeSymbol nts && nts.TypeArguments.Length == 1)
        {
            return nts.TypeArguments[0].ToGlobalName();
        }
        return "global::System.Object";
    }

    private static string GetValueTaskInnerType(ITypeSymbol valueTaskType)
    {
        if (valueTaskType is INamedTypeSymbol nts && nts.TypeArguments.Length == 1)
        {
            return nts.TypeArguments[0].ToGlobalName();
        }
        return "global::System.Object";
    }

    private static string GetTaskInnerType(ITypeSymbol taskType)
    {
        if (taskType is INamedTypeSymbol nts && nts.TypeArguments.Length == 1)
        {
            return nts.TypeArguments[0].ToGlobalName();
        }
        return "global::System.Object";
    }

    private static string EmitGenericParameterList(IMethodSymbol method)
    {
        if (!method.IsGenericMethod) return string.Empty;
        return $"<{string.Join(", ", method.TypeParameters.Select(EmitTypeParameterWithAttributes))}>";
    }

    // When invoking the target from within the same generic method, pass through the same type parameters.
    private static string EmitGenericTypeArgumentList(IMethodSymbol method)
        => EmitGenericParameterList(method);

    private static void EmitGenericConstraints(StringBuilder sb, IMethodSymbol method, string indent)
    {
        if (!method.IsGenericMethod) return;

        // 对于 override 方法，不需要重新声明约束（约束从基方法继承）
        // 只在非 override 的泛型方法中声明约束
        // 注意：这里的 method 是 service method，如果是 class proxy 的 override 方法，
        // 我们不应该重新声明约束

        // 检查是否是 override 方法（通过检查 IsOverride 属性）
        if (method.IsOverride) return;

        foreach (var tp in method.TypeParameters)
        {
            var parts = new List<string>();
            if (tp.HasNotNullConstraint) parts.Add("notnull");
            if (tp.HasReferenceTypeConstraint) parts.Add("class");
            if (tp.HasUnmanagedTypeConstraint) parts.Add("unmanaged");
            if (tp.HasValueTypeConstraint) parts.Add("struct");

            foreach (var ct in tp.ConstraintTypes)
            {
                parts.Add(ct.ToGlobalName());
            }

            if (tp.HasConstructorConstraint) parts.Add("new()");
            if (parts.Count == 0) continue;

            sb.Append(indent)
              .Append("where ")
              .Append(tp.Name)
              .Append(" : ")
              .Append(string.Join(", ", parts))
              .AppendLine();
        }
    }

    private static void EmitTypeParameterConstraints(StringBuilder sb, ImmutableArray<ITypeParameterSymbol> typeParams, string indent)
    {
        foreach (var tp in typeParams)
        {
            var parts = new List<string>();
            if (tp.HasNotNullConstraint) parts.Add("notnull");
            if (tp.HasReferenceTypeConstraint) parts.Add("class");
            if (tp.HasUnmanagedTypeConstraint) parts.Add("unmanaged");
            if (tp.HasValueTypeConstraint) parts.Add("struct");

            foreach (var ct in tp.ConstraintTypes)
            {
                parts.Add(ct.ToGlobalName());
            }

            if (tp.HasConstructorConstraint) parts.Add("new()");
            if (parts.Count == 0) continue;

            sb.Append(indent)
              .Append("where ")
              .Append(tp.Name)
              .Append(" : ")
              .Append(string.Join(", ", parts))
              .AppendLine();
        }
    }

    // ── Attribute forwarding ──────────────────────────────────────────────

    // Compiler-generated attributes that must never be forwarded.
    private static readonly HashSet<string> CompilerGeneratedAttributeNames = new()
    {
        "System.Runtime.CompilerServices.NullableContextAttribute",
        "System.Runtime.CompilerServices.NullableAttribute",
        "System.Runtime.CompilerServices.CompilerGeneratedAttribute",
        "System.Runtime.CompilerServices.IsReadOnlyAttribute",
        "System.Runtime.CompilerServices.IsByRefLikeAttribute",
        "System.Runtime.CompilerServices.IsExternalInitAttribute",
        "System.Runtime.CompilerServices.PreserveBaseOverridesAttribute",
        "System.Runtime.CompilerServices.PrimaryConstructorParametersAttribute",
    };

    // Whitelist of attributes to forward on types, methods, and parameters.
    // Type parameters use a separate rule (any non-blacklisted attribute is forwarded).
    //
    // NOTE: System.Runtime.CompilerServices.ParamCollectionAttribute is intentionally
    // NOT listed here. The compiler synthesises it automatically when the `params`
    // keyword is used on a collection type. Emitting it explicitly alongside `params`
    // would cause CS0674 ("Use the `params` keyword instead").
    private static readonly HashSet<string> ForwardedAttributeNames = new()
    {
        "System.Diagnostics.CodeAnalysis.ExperimentalAttribute",
        "System.Runtime.CompilerServices.CollectionBuilderAttribute",
        "System.Runtime.CompilerServices.CallerArgumentExpressionAttribute",
    };

    private static bool IsAspectCoreMarkerAttribute(INamedTypeSymbol attrType)
    {
        var ns = attrType.ContainingNamespace?.ToDisplayString();
        return ns == "AspectCore.DynamicProxy" || ns == "AspectCore.Abstractions.DynamicProxy";
    }

    private static string GetFullAttributeName(INamedTypeSymbol attrType)
    {
        var ns = attrType.ContainingNamespace?.ToDisplayString();
        return string.IsNullOrEmpty(ns) ? attrType.Name : $"{ns}.{attrType.Name}";
    }

    private static bool ShouldForwardAttribute(AttributeData attr, bool isTypeParameter)
    {
        var attrClass = attr.AttributeClass;
        if (attrClass is null) return false;

        var fullName = GetFullAttributeName(attrClass);

        // Skip compiler-generated attributes.
        if (CompilerGeneratedAttributeNames.Contains(fullName)) return false;

        // Skip AspectCore marker attributes (already emitted or must not be duplicated).
        if (IsAspectCoreMarkerAttribute(attrClass)) return false;

        // For type parameters: forward any non-blacklisted attribute.
        if (isTypeParameter) return true;

        // For types, methods, and parameters: only forward whitelisted attributes.
        return ForwardedAttributeNames.Contains(fullName);
    }

    private static string FormatTypedConstant(TypedConstant constant)
    {
        if (constant.Value is null) return "null";

        switch (constant.Kind)
        {
            case TypedConstantKind.Type:
                if (constant.Value is ITypeSymbol typeSymbol)
                    return $"typeof({typeSymbol.ToGlobalName()})";
                return "null";

            case TypedConstantKind.Array:
                var elements = ((ImmutableArray<TypedConstant>)constant.Value)
                    .Select(FormatTypedConstant);
                return $"new[] {{ {string.Join(", ", elements)} }}";

            case TypedConstantKind.Enum:
                return constant.Value.ToString() ?? "null";

            case TypedConstantKind.Primitive:
                if (constant.Value is string str)
                    return $"\"{str.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
                if (constant.Value is bool b)
                    return b ? "true" : "false";
                return constant.Value.ToString() ?? "null";

            default:
                return constant.Value.ToString() ?? "null";
        }
    }

    private static string FormatAttributeArguments(AttributeData attr)
    {
        var args = new List<string>();

        foreach (var arg in attr.ConstructorArguments)
        {
            args.Add(FormatTypedConstant(arg));
        }

        foreach (var named in attr.NamedArguments)
        {
            args.Add($"{named.Key} = {FormatTypedConstant(named.Value)}");
        }

        return string.Join(", ", args);
    }

    /// <summary>
    /// Emits forwarded attributes for the given symbol, one per line, each prefixed with indent.
    /// Skips compiler-generated and AspectCore marker attributes; forwards only whitelisted
    /// attributes (or any non-blacklisted attribute when isTypeParameter is true).
    /// </summary>
    private static void EmitAttributes(StringBuilder sb, ISymbol symbol, string indent, bool isTypeParameter = false)
    {
        foreach (var attr in symbol.GetAttributes())
        {
            if (!ShouldForwardAttribute(attr, isTypeParameter)) continue;

            var attrName = attr.AttributeClass!.ToGlobalName();
            var args = FormatAttributeArguments(attr);

            sb.Append(indent).Append('[').Append(attrName);
            if (!string.IsNullOrEmpty(args))
            {
                sb.Append('(').Append(args).Append(')');
            }
            sb.AppendLine("]");
        }
    }

    /// <summary>
    /// Returns a string of forwarded attributes suitable for inline use (e.g. in parameter
    /// declarations or type parameter lists). Returns an empty string when no attributes apply.
    /// </summary>
    private static string EmitAttributesInline(ISymbol symbol, bool isTypeParameter = false)
    {
        var sb = new StringBuilder();
        foreach (var attr in symbol.GetAttributes())
        {
            if (!ShouldForwardAttribute(attr, isTypeParameter)) continue;

            var attrName = attr.AttributeClass!.ToGlobalName();
            var args = FormatAttributeArguments(attr);

            sb.Append('[').Append(attrName);
            if (!string.IsNullOrEmpty(args))
            {
                sb.Append('(').Append(args).Append(')');
            }
            sb.Append("] ");
        }
        return sb.ToString();
    }

    /// <summary>
    /// Emits a type parameter name with any forwarded attributes prepended (for C# 13
    /// type parameter attributes such as [Experimental]).
    /// </summary>
    private static string EmitTypeParameterWithAttributes(ITypeParameterSymbol tp)
    {
        var attrs = EmitAttributesInline(tp, isTypeParameter: true);
        return $"{attrs}{tp.Name}";
    }
}

internal enum ReturnKindKind
{
    Void,
    Sync,
    Task,
    TaskOfT,
    ValueTask,
    ValueTaskOfT,
    AsyncEnumerable,
    // C# 7.0 ref / ref readonly return. Value-based pipeline materialises the
    // result into a StrongBox<T> and returns `ref __box.Value`.
    RefSync,
}

internal static class ReturnKind
{
    public static ReturnKindKind Determine(IMethodSymbol method)
    {
        if (method.ReturnsVoid) return ReturnKindKind.Void;

        // C# 7.0 ref / ref readonly return. RefKind distinguishes these from a
        // plain value return; the async return kinds cannot be byref.
        if (method.RefKind is RefKind.Ref or RefKind.RefReadOnly)
            return ReturnKindKind.RefSync;

        var rt = method.ReturnType;
        if (rt is INamedTypeSymbol named)
        {
            if (named.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Threading.Tasks.Task")
                return ReturnKindKind.Task;
            if (named.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Threading.Tasks.Task<T>")
                return ReturnKindKind.TaskOfT;
            if (named.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Threading.Tasks.ValueTask")
                return ReturnKindKind.ValueTask;
            if (named.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Threading.Tasks.ValueTask<T>")
                return ReturnKindKind.ValueTaskOfT;
            if (named.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Collections.Generic.IAsyncEnumerable<T>")
                return ReturnKindKind.AsyncEnumerable;
        }
        return ReturnKindKind.Sync;
    }
}
