using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace AspectCore.SourceGenerator;

internal static class ProxyEmitter
{
    public static string? EmitInterfaceProxy(Compilation compilation, ProxyEntry entry, SourceProductionContext context)
    {
        if (entry.ServiceType.TypeKind != TypeKind.Interface)
        {
            return null;
        }

        if (entry.ServiceType.GetMembers().OfType<IEventSymbol>().Any())
        {
            var ev = entry.ServiceType.GetMembers().OfType<IEventSymbol>().First();
            context.ReportDiagnostic(GeneratorDiagnostics.UnsupportedEvent(entry.ServiceType, ev));
            return null;
        }

        // Generic methods are supported (proxy method emits generic arity + MakeGenericMethod).

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {entry.ProxyNamespace}");
        sb.AppendLine("{");

        var ifaceName = entry.ServiceType.ToGlobalName();
        var proxyName = entry.ProxyTypeName;
        var implementationType = entry.ImplementationType;

        // stub
        // NOTE: namespace-level types cannot be private; keep this internal.
        sb.AppendLine($"    internal sealed class {proxyName}__Stub : {ifaceName}");
        sb.AppendLine("    {");
        EmitInterfaceStubMembers(sb, entry.ServiceType);
        sb.AppendLine("    }");
        sb.AppendLine();

        // proxy
        sb.AppendLine("    [global::AspectCore.DynamicProxy.NonAspect]");
        sb.AppendLine("    [global::AspectCore.DynamicProxy.Dynamically]");
        sb.AppendLine($"    public sealed class {proxyName} : {ifaceName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::AspectCore.DynamicProxy.IAspectActivatorFactory _activatorFactory;");
        sb.AppendLine($"        private readonly {ifaceName} _implementation;");
        sb.AppendLine("        private global::AspectCore.DynamicProxy.IAspectValidator _validator;");
        sb.AppendLine();

        // ctors (both required shapes)
        sb.AppendLine($"        public {proxyName}(global::AspectCore.DynamicProxy.IAspectActivatorFactory activatorFactory)");
        sb.AppendLine("        {");
        sb.AppendLine("            _activatorFactory = activatorFactory ?? throw new ArgumentNullException(nameof(activatorFactory));");
        sb.AppendLine($"            _implementation = new {proxyName}__Stub();");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public {proxyName}(global::AspectCore.DynamicProxy.IAspectActivatorFactory activatorFactory, {ifaceName} implementation)");
        sb.AppendLine("        {");
        sb.AppendLine("            _activatorFactory = activatorFactory ?? throw new ArgumentNullException(nameof(activatorFactory));");
        sb.AppendLine("            _implementation = implementation; // allow null (matches runtime behavior)");
        sb.AppendLine("        }");
        sb.AppendLine();

        EmitValidatorHelpers(sb);
        sb.AppendLine();

        EmitInterfaceProxyMembers(sb, compilation, entry.ServiceType, implementationType, proxyName, ifaceName);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string? EmitClassProxy(Compilation compilation, ProxyEntry entry, SourceProductionContext context)
    {
        if (entry.ServiceType.TypeKind != TypeKind.Class || entry.ImplementationType is null)
        {
            return null;
        }

        if (entry.ServiceType.GetMembers().OfType<IEventSymbol>().Any())
        {
            var ev = entry.ServiceType.GetMembers().OfType<IEventSymbol>().First();
            context.ReportDiagnostic(GeneratorDiagnostics.UnsupportedEvent(entry.ServiceType, ev));
            return null;
        }

        // Generic methods are supported (proxy method emits generic arity + MakeGenericMethod).

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {entry.ProxyNamespace}");
        sb.AppendLine("{");

        var serviceName = entry.ServiceType.ToGlobalName();
        var implName = entry.ImplementationType.ToGlobalName();
        var proxyName = entry.ProxyTypeName;

        sb.AppendLine("    [global::AspectCore.DynamicProxy.NonAspect]");
        sb.AppendLine("    [global::AspectCore.DynamicProxy.Dynamically]");
        sb.AppendLine($"    public sealed class {proxyName} : {implName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::AspectCore.DynamicProxy.IAspectActivatorFactory _activatorFactory;");
        sb.AppendLine($"        private readonly {serviceName} _implementation;");
        sb.AppendLine("        private global::AspectCore.DynamicProxy.IAspectValidator _validator;");
        sb.AppendLine();

        EmitClassConstructors(sb, entry.ImplementationType, proxyName);
        sb.AppendLine();
        EmitValidatorHelpers(sb);
        sb.AppendLine();

        EmitClassProxyMembers(sb, compilation, entry.ServiceType, entry.ImplementationType, proxyName, serviceName);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitValidatorHelpers(StringBuilder sb)
    {
        sb.AppendLine("        private global::AspectCore.DynamicProxy.IAspectValidator GetValidator()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_validator != null) return _validator;");
        sb.AppendLine("            var accessor = _activatorFactory as global::AspectCore.DynamicProxy.IAspectConfigurationAccessor;");
        sb.AppendLine("            if (accessor == null) return null;");
        sb.AppendLine("            _validator = new global::AspectCore.DynamicProxy.AspectValidatorBuilder(accessor.AspectConfiguration).Build();");
        sb.AppendLine("            return _validator;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private bool ShouldIntercept(MethodInfo serviceMethod, MethodInfo implementationMethod)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (global::AspectCore.DynamicProxy.ReflectionUtils.IsNonAspect(serviceMethod)) return false;");
        sb.AppendLine("            var v = GetValidator();");
        sb.AppendLine("            if (v == null) return false;");
        sb.AppendLine("            return v.Validate(serviceMethod, true) || v.Validate(implementationMethod, false);");
        sb.AppendLine("        }");
    }

    private static void EmitInterfaceStubMembers(StringBuilder sb, INamedTypeSymbol iface)
    {
        // properties
        foreach (var prop in iface.GetMembers().OfType<IPropertySymbol>())
        {
            var typeName = prop.Type.ToGlobalName();
            if (prop.IsIndexer)
            {
                // minimal indexer stub
                sb.Append("        public ").Append(typeName).Append(" this[");
                sb.Append(string.Join(", ", prop.Parameters.Select(p => $"{p.Type.ToGlobalName()} {p.Name}")));
                sb.AppendLine("]");
                sb.AppendLine("        {");
                if (prop.GetMethod is not null)
                    sb.AppendLine($"            get => default({typeName});");
                if (prop.SetMethod is not null)
                    sb.AppendLine("            set { }");
                sb.AppendLine("        }");
            }
            else
            {
                sb.Append("        public ").Append(typeName).Append(' ').Append(prop.Name).AppendLine();
                sb.AppendLine("        {");
                if (prop.GetMethod is not null)
                    sb.AppendLine($"            get => default({typeName});");
                if (prop.SetMethod is not null)
                    sb.AppendLine("            set { }");
                sb.AppendLine("        }");
            }
            sb.AppendLine();
        }

        // methods
        // Only emit stubs for abstract members. For default interface methods, omit the member so that
        // runtime dispatch can use the DIM implementation.
        foreach (var method in iface.GetMembers().OfType<IMethodSymbol>()
                     .Where(m => m.MethodKind == MethodKind.Ordinary)
                     .Where(m => m.IsAbstract))
        {
            EmitStubMethod(sb, method);
            sb.AppendLine();
        }
    }

    private static void EmitStubMethod(StringBuilder sb, IMethodSymbol method)
    {
        sb.Append("        public ");
        sb.Append(method.ReturnsVoid ? "void" : method.ReturnType.ToGlobalName());
        sb.Append(' ').Append(method.Name).Append(EmitGenericParameterList(method)).Append('(');
        sb.Append(string.Join(", ", method.Parameters.Select(EmitParameterDecl)));
        sb.AppendLine(")");
        EmitGenericConstraints(sb, method, indent: "        ");
        sb.AppendLine("        {");
        foreach (var p in method.Parameters)
        {
            if (p.RefKind == RefKind.Out)
            {
                sb.AppendLine($"            {p.Name} = default({p.Type.ToGlobalName()});");
            }
        }

        if (!method.ReturnsVoid)
        {
            sb.AppendLine($"            return default({method.ReturnType.ToGlobalName()});");
        }
        sb.AppendLine("        }");
    }

    private static void EmitInterfaceProxyMembers(StringBuilder sb, Compilation compilation, INamedTypeSymbol iface, INamedTypeSymbol? implementationType, string proxyName, string ifaceName)
    {
        // meta cache
        sb.AppendLine("        private static class __Meta");
        sb.AppendLine("        {");

        var methods = iface.GetMembers().OfType<IMethodSymbol>().Where(m => m.MethodKind == MethodKind.Ordinary).ToList();
        var props = iface.GetMembers().OfType<IPropertySymbol>().ToList();

        foreach (var m in methods)
        {
            EmitMethodMeta(sb, iface, implementationType, proxyName, m);
        }
        foreach (var p in props)
        {
            if (p.GetMethod is not null) EmitMethodMeta(sb, iface, implementationType, proxyName, p.GetMethod);
            if (p.SetMethod is not null) EmitMethodMeta(sb, iface, implementationType, proxyName, p.SetMethod);
        }

        sb.AppendLine("        }");
        sb.AppendLine();

        // properties
        foreach (var prop in props)
        {
            EmitProxyProperty(sb, iface, implementationType, proxyName, ifaceName, prop);
            sb.AppendLine();
        }

        // methods
        foreach (var method in methods)
        {
            EmitProxyMethod(sb, iface, implementationType, proxyName, ifaceName, method, callTargetExpr: $"_implementation.{method.Name}");
            sb.AppendLine();
        }
    }

    private static void EmitClassConstructors(StringBuilder sb, INamedTypeSymbol implType, string proxyName)
    {
        foreach (var ctor in implType.InstanceConstructors.Where(c => c.DeclaredAccessibility is Accessibility.Public or Accessibility.Protected or Accessibility.ProtectedOrInternal or Accessibility.ProtectedAndInternal))
        {
            sb.Append("        public ").Append(proxyName).Append("(global::AspectCore.DynamicProxy.IAspectActivatorFactory activatorFactory");
            if (ctor.Parameters.Length > 0)
            {
                sb.Append(", ");
                sb.Append(string.Join(", ", ctor.Parameters.Select(p => $"{p.Type.ToGlobalName()} {p.Name}")));
            }
            sb.Append(')');
            sb.Append(" : base(");
            sb.Append(string.Join(", ", ctor.Parameters.Select(p => p.Name)));
            sb.AppendLine(")");
            sb.AppendLine("        {");
            sb.AppendLine("            _activatorFactory = activatorFactory ?? throw new ArgumentNullException(nameof(activatorFactory));");
            sb.AppendLine("            _implementation = this;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }

    private static void EmitClassProxyMembers(StringBuilder sb, Compilation compilation, INamedTypeSymbol serviceType, INamedTypeSymbol implType, string proxyName, string serviceName)
    {
        var methods = serviceType.GetMembers().OfType<IMethodSymbol>()
            .Where(m => m.MethodKind == MethodKind.Ordinary)
            .Where(IsOverridable)
            .ToList();
        var props = serviceType.GetMembers().OfType<IPropertySymbol>()
            .Where(p => (p.GetMethod is not null && IsOverridable(p.GetMethod)) || (p.SetMethod is not null && IsOverridable(p.SetMethod)))
            .ToList();

        sb.AppendLine("        private static class __Meta");
        sb.AppendLine("        {");
        foreach (var m in methods)
        {
            EmitMethodMeta(sb, serviceType, implType, proxyName, m);
        }
        foreach (var p in props)
        {
            if (p.GetMethod is not null) EmitMethodMeta(sb, serviceType, implType, proxyName, p.GetMethod);
            if (p.SetMethod is not null) EmitMethodMeta(sb, serviceType, implType, proxyName, p.SetMethod);
        }
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach (var prop in props)
        {
            EmitProxyProperty(sb, serviceType, implType, proxyName, serviceName, prop, isOverride: true);
            sb.AppendLine();
        }

        foreach (var method in methods)
        {
            EmitProxyMethod(sb, serviceType, implType, proxyName, serviceName, method, callTargetExpr: $"base.{method.Name}", isOverride: true);
            sb.AppendLine();
        }
    }

    private static bool IsOverridable(IMethodSymbol method)
    {
        if (method.IsStatic) return false;
        if (!method.IsVirtual) return false;
        if (method.IsSealed) return false;
        if (method.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Protected or Accessibility.ProtectedOrInternal or Accessibility.ProtectedAndInternal))
            return false;
        if (method.Name == "Finalize") return false;
        return true;
    }

    private static void EmitMethodMeta(StringBuilder sb, INamedTypeSymbol serviceType, INamedTypeSymbol? implementationType, string proxyTypeName, IMethodSymbol method)
    {
        var suffix = GetMethodId(method);
        var serviceMethodField = $"Service_{suffix}";
        var implMethodField = $"Impl_{suffix}";
        var proxyMethodField = $"Proxy_{suffix}";

        var serviceTypeExpr = $"typeof({serviceType.ToGlobalName()})";
        var proxyTypeExpr = $"typeof(global::{Naming.GeneratedProxyNamespace}.{proxyTypeName})";

        if (!method.IsGenericMethod)
        {
            var paramTypesExpr = EmitParameterTypesArray(method);
            sb.AppendLine($"            internal static readonly MethodInfo {serviceMethodField} = {serviceTypeExpr}.GetMethod(\"{method.Name}\", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic, binder: null, types: {paramTypesExpr}, modifiers: null);");
        }
        else
        {
            var findName = $"FindService_{suffix}";
            sb.AppendLine($"            internal static readonly MethodInfo {serviceMethodField} = {findName}();");
            sb.AppendLine($"            private static MethodInfo {findName}()");
            sb.AppendLine("            {");
            sb.AppendLine($"                foreach (var m in {serviceTypeExpr}.GetMethods(global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic))");
            sb.AppendLine("                {");
            sb.AppendLine($"                    if (m.Name != \"{method.Name}\") continue;");
            sb.AppendLine("                    if (!m.IsGenericMethodDefinition) continue;");
            sb.AppendLine($"                    if (m.GetGenericArguments().Length != {method.TypeParameters.Length}) continue;");
            sb.AppendLine("                    var ps = m.GetParameters();");
            sb.AppendLine($"                    if (ps.Length != {method.Parameters.Length}) continue;");

            for (var i = 0; i < method.Parameters.Length; i++)
            {
                var p = method.Parameters[i];
                var wantsByRef = p.RefKind is RefKind.Ref or RefKind.Out or RefKind.In;
                var expectsGenericParam = p.Type is ITypeParameterSymbol;
                var expectedTypeExpr = expectsGenericParam ? null : $"typeof({p.Type.ToGlobalName()})";

                sb.AppendLine($"                    var p{i} = ps[{i}].ParameterType;");
                if (wantsByRef)
                {
                    sb.AppendLine($"                    if (!p{i}.IsByRef) continue;");
                    sb.AppendLine($"                    p{i} = p{i}.GetElementType();");
                }
                else
                {
                    sb.AppendLine($"                    if (p{i}.IsByRef) continue;");
                }

                if (expectsGenericParam)
                {
                    sb.AppendLine($"                    if (p{i} == null || !p{i}.IsGenericParameter) continue;");
                }
                else
                {
                    sb.AppendLine($"                    if (p{i} != {expectedTypeExpr}) continue;");
                }
            }

            sb.AppendLine("                    return m;");
            sb.AppendLine("                }");
            sb.AppendLine($"                throw new MissingMethodException({serviceTypeExpr}.FullName, \"{method.Name}\");");
            sb.AppendLine("            }");
        }

        if (implementationType is null)
        {
            // no target: use service method itself
            sb.AppendLine($"            internal static readonly MethodInfo {implMethodField} = {serviceMethodField};");
        }
        else
        {
            sb.AppendLine($"            internal static readonly MethodInfo {implMethodField} = global::AspectCore.DynamicProxy.ReflectionUtils.GetMethodBySignature(typeof({implementationType.ToGlobalName()}).GetTypeInfo(), {serviceMethodField});");
        }

        if (!method.IsGenericMethod)
        {
            var paramTypesExpr = EmitParameterTypesArray(method);
            sb.AppendLine($"            internal static readonly MethodInfo {proxyMethodField} = {proxyTypeExpr}.GetMethod(\"{method.Name}\", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic, binder: null, types: {paramTypesExpr}, modifiers: null);");
        }
        else
        {
            var findName = $"FindProxy_{suffix}";
            sb.AppendLine($"            internal static readonly MethodInfo {proxyMethodField} = {findName}();");
            sb.AppendLine($"            private static MethodInfo {findName}()");
            sb.AppendLine("            {");
            sb.AppendLine($"                foreach (var m in {proxyTypeExpr}.GetMethods(global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic))");
            sb.AppendLine("                {");
            sb.AppendLine($"                    if (m.Name != \"{method.Name}\") continue;");
            sb.AppendLine("                    if (!m.IsGenericMethodDefinition) continue;");
            sb.AppendLine($"                    if (m.GetGenericArguments().Length != {method.TypeParameters.Length}) continue;");
            sb.AppendLine("                    var ps = m.GetParameters();");
            sb.AppendLine($"                    if (ps.Length != {method.Parameters.Length}) continue;");

            for (var i = 0; i < method.Parameters.Length; i++)
            {
                var p = method.Parameters[i];
                var wantsByRef = p.RefKind is RefKind.Ref or RefKind.Out or RefKind.In;
                var expectsGenericParam = p.Type is ITypeParameterSymbol;
                var expectedTypeExpr = expectsGenericParam ? null : $"typeof({p.Type.ToGlobalName()})";

                sb.AppendLine($"                    var p{i} = ps[{i}].ParameterType;");
                if (wantsByRef)
                {
                    sb.AppendLine($"                    if (!p{i}.IsByRef) continue;");
                    sb.AppendLine($"                    p{i} = p{i}.GetElementType();");
                }
                else
                {
                    sb.AppendLine($"                    if (p{i}.IsByRef) continue;");
                }

                if (expectsGenericParam)
                {
                    sb.AppendLine($"                    if (p{i} == null || !p{i}.IsGenericParameter) continue;");
                }
                else
                {
                    sb.AppendLine($"                    if (p{i} != {expectedTypeExpr}) continue;");
                }
            }

            sb.AppendLine("                    return m;");
            sb.AppendLine("                }");
            sb.AppendLine($"                throw new MissingMethodException({proxyTypeExpr}.FullName, \"{method.Name}\");");
            sb.AppendLine("            }");
        }
        sb.AppendLine();
    }

    private static void EmitProxyProperty(StringBuilder sb, INamedTypeSymbol serviceType, INamedTypeSymbol? implementationType, string proxyTypeName, string declaredTypeName, IPropertySymbol prop, bool isOverride = false)
    {
        var propTypeName = prop.Type.ToGlobalName();

        if (prop.IsIndexer)
        {
            sb.Append("        public ");
            if (isOverride) sb.Append("override ");
            sb.Append(propTypeName).Append(" this[");
            sb.Append(string.Join(", ", prop.Parameters.Select(p => $"{p.Type.ToGlobalName()} {p.Name}")));
            sb.AppendLine("]");
        }
        else
        {
            sb.Append("        public ");
            if (isOverride) sb.Append("override ");
            sb.Append(propTypeName).Append(' ').Append(prop.Name).AppendLine();
        }

        sb.AppendLine("        {");
        if (prop.GetMethod is not null)
        {
            EmitAccessorBody(sb, serviceType, implementationType, proxyTypeName, prop.GetMethod, declaredTypeName, prop, accessorKind: "get", callExpr: prop.IsIndexer ? "base" : "base", isOverride: isOverride);
        }
        if (prop.SetMethod is not null)
        {
            EmitAccessorBody(sb, serviceType, implementationType, proxyTypeName, prop.SetMethod, declaredTypeName, prop, accessorKind: "set", callExpr: prop.IsIndexer ? "base" : "base", isOverride: isOverride);
        }
        sb.AppendLine("        }");
    }

    private static void EmitAccessorBody(StringBuilder sb, INamedTypeSymbol serviceType, INamedTypeSymbol? implementationType, string proxyTypeName, IMethodSymbol accessor, string declaredTypeName, IPropertySymbol prop, string accessorKind, string callExpr, bool isOverride)
    {
        // Use same emission as method, but inside property block.
        // We'll generate a local function body as statement block.

        var suffix = GetMethodId(accessor);
        var serviceMethodField = $"__Meta.Service_{suffix}";
        var implMethodField = $"__Meta.Impl_{suffix}";
        var proxyMethodField = $"__Meta.Proxy_{suffix}";

        if (accessorKind == "get")
        {
            sb.AppendLine("            get");
            sb.AppendLine("            {");
            EmitProxyInvokeBody(
                sb,
                accessor,
                serviceMethodField,
                implMethodField,
                proxyMethodField,
                directCall: prop.IsIndexer
                    ? $"{(isOverride ? "base" : "_implementation")}[{string.Join(", ", prop.Parameters.Select(p => p.Name))}]"
                    : $"{(isOverride ? "base" : "_implementation")}.{prop.Name}",
                resolveImplementationMethodByInstance: implementationType is null,
                interfaceStubTypeName: implementationType is null ? $"{proxyTypeName}__Stub" : null);
            sb.AppendLine("            }");
        }
        else
        {
            sb.AppendLine("            set");
            sb.AppendLine("            {");
            EmitProxyInvokeBody(
                sb,
                accessor,
                serviceMethodField,
                implMethodField,
                proxyMethodField,
                directCall: prop.IsIndexer
                    ? $"{(isOverride ? "base" : "_implementation")}[{string.Join(", ", prop.Parameters.Select(p => p.Name))}] = value"
                    : $"{(isOverride ? "base" : "_implementation")}.{prop.Name} = value",
                resolveImplementationMethodByInstance: implementationType is null,
                interfaceStubTypeName: implementationType is null ? $"{proxyTypeName}__Stub" : null);
            sb.AppendLine("            }");
        }
    }

    private static void EmitProxyMethod(StringBuilder sb, INamedTypeSymbol serviceType, INamedTypeSymbol? implementationType, string proxyTypeName, string declaredTypeName, IMethodSymbol method, string callTargetExpr, bool isOverride = false)
    {
        sb.Append("        public ");
        if (isOverride) sb.Append("override ");
        sb.Append(method.ReturnsVoid ? "void" : method.ReturnType.ToGlobalName());
        sb.Append(' ').Append(method.Name).Append(EmitGenericParameterList(method)).Append('(');
        sb.Append(string.Join(", ", method.Parameters.Select(EmitParameterDecl)));
        sb.AppendLine(")");
        EmitGenericConstraints(sb, method, indent: "        ");
        sb.AppendLine("        {");

        var suffix = GetMethodId(method);
        EmitProxyInvokeBody(
            sb,
            method,
            serviceMethodField: $"__Meta.Service_{suffix}",
            implMethodField: $"__Meta.Impl_{suffix}",
            proxyMethodField: $"__Meta.Proxy_{suffix}",
            directCall: $"{callTargetExpr}{EmitGenericTypeArgumentList(method)}({string.Join(", ", method.Parameters.Select(EmitArgument))})",
            resolveImplementationMethodByInstance: implementationType is null,
            interfaceStubTypeName: implementationType is null ? $"{proxyTypeName}__Stub" : null);

        sb.AppendLine("        }");
    }

    private static void EmitProxyInvokeBody(
        StringBuilder sb,
        IMethodSymbol method,
        string serviceMethodField,
        string implMethodField,
        string proxyMethodField,
        string directCall,
        bool resolveImplementationMethodByInstance,
        string? interfaceStubTypeName)
    {
        var argCount = method.Parameters.Length;
        sb.AppendLine($"            var __serviceMethod = {serviceMethodField};");
        sb.AppendLine($"            var __implMethod = {implMethodField};");
        sb.AppendLine($"            var __proxyMethod = {proxyMethodField};");

        if (resolveImplementationMethodByInstance)
        {
            sb.AppendLine($"            if (_implementation is not null && !(_implementation is {interfaceStubTypeName}))");
            sb.AppendLine("            {");
            sb.AppendLine("                try");
            sb.AppendLine("                {");
            sb.AppendLine("                    __implMethod = global::AspectCore.DynamicProxy.ReflectionUtils.GetMethodBySignature(_implementation.GetType().GetTypeInfo(), __serviceMethod);");
            sb.AppendLine("                }");
            sb.AppendLine("                catch");
            sb.AppendLine("                {");
            sb.AppendLine("                    // ignore and fall back to service method\n");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        if (method.IsGenericMethod)
        {
            sb.AppendLine($"            var __genericArgs = new[] {{ {string.Join(", ", method.TypeParameters.Select(tp => $"typeof({tp.Name})"))} }};");
            sb.AppendLine("            if (__serviceMethod.IsGenericMethodDefinition) __serviceMethod = __serviceMethod.MakeGenericMethod(__genericArgs);");
            sb.AppendLine("            if (__implMethod.IsGenericMethodDefinition) __implMethod = __implMethod.MakeGenericMethod(__genericArgs);");
            sb.AppendLine("            if (__proxyMethod.IsGenericMethodDefinition) __proxyMethod = __proxyMethod.MakeGenericMethod(__genericArgs);");
            sb.AppendLine();
        }
        sb.AppendLine("            if (!ShouldIntercept(__serviceMethod, __implMethod))");
        sb.AppendLine("            {");
        if (method.ReturnsVoid)
        {
            sb.AppendLine($"                {directCall};");
            sb.AppendLine("                return;");
        }
        else
        {
            sb.AppendLine($"                return {directCall};");
        }
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine($"            var __args = new object[{argCount}];");
        for (var i = 0; i < argCount; i++)
        {
            var p = method.Parameters[i];
            if (p.RefKind == RefKind.Out)
            {
                sb.AppendLine($"            __args[{i}] = default({p.Type.ToGlobalName()});");
            }
            else
            {
                sb.AppendLine($"            __args[{i}] = {p.Name};");
            }
        }
        sb.AppendLine();
        sb.AppendLine("            var __ctx = new global::AspectCore.DynamicProxy.AspectActivatorContext(");
        sb.AppendLine("                __serviceMethod,");
        sb.AppendLine("                __implMethod,");
        sb.AppendLine("                __proxyMethod,");
        sb.AppendLine("                _implementation,");
        sb.AppendLine("                this,");
        sb.AppendLine("                __args);");
        sb.AppendLine();
        sb.AppendLine("            var __activator = _activatorFactory.Create();");

        var rk = ReturnKind.Determine(method);
        switch (rk)
        {
            case ReturnKindKind.Void:
                sb.AppendLine("            __activator.Invoke<object>(__ctx);");
                break;
            case ReturnKindKind.Task:
                sb.AppendLine("            var __task = __activator.InvokeTask<object>(__ctx);");
                break;
            case ReturnKindKind.TaskOfT:
                sb.AppendLine($"            var __task = __activator.InvokeTask<{GetTaskInnerType(method.ReturnType)}>(__ctx);");
                break;
            case ReturnKindKind.ValueTask:
                sb.AppendLine("            var __vt = __activator.InvokeValueTask<object>(__ctx);");
                break;
            case ReturnKindKind.ValueTaskOfT:
                sb.AppendLine($"            var __vt = __activator.InvokeValueTask<{GetValueTaskInnerType(method.ReturnType)}>(__ctx);");
                break;
            case ReturnKindKind.Sync:
                sb.AppendLine($"            var __ret = __activator.Invoke<{method.ReturnType.ToGlobalName()}>(__ctx);");
                break;
        }

        // write back ref/out
        for (var i = 0; i < argCount; i++)
        {
            var p = method.Parameters[i];
            if (p.RefKind is RefKind.Ref or RefKind.Out)
            {
                sb.AppendLine($"            {p.Name} = ({p.Type.ToGlobalName()})__args[{i}];");
            }
        }

        // return
        switch (rk)
        {
            case ReturnKindKind.Void:
                sb.AppendLine("            return;");
                break;
            case ReturnKindKind.Task:
                sb.AppendLine("            return __task; // Task<object> upcast to Task");
                break;
            case ReturnKindKind.TaskOfT:
                sb.AppendLine("            return __task;");
                break;
            case ReturnKindKind.ValueTask:
                sb.AppendLine("            return new ValueTask(__vt.AsTask());");
                break;
            case ReturnKindKind.ValueTaskOfT:
                sb.AppendLine("            return __vt;");
                break;
            case ReturnKindKind.Sync:
                sb.AppendLine("            return __ret;");
                break;
        }
    }

    private static string EmitParameterDecl(IParameterSymbol p)
    {
        var prefix = p.RefKind switch
        {
            RefKind.Ref => "ref ",
            RefKind.Out => "out ",
            RefKind.In => "in ",
            _ => ""
        };
        return $"{prefix}{p.Type.ToGlobalName()} {p.Name}";
    }

    private static string EmitArgument(IParameterSymbol p)
    {
        var prefix = p.RefKind switch
        {
            RefKind.Ref => "ref ",
            RefKind.Out => "out ",
            RefKind.In => "in ",
            _ => ""
        };
        return $"{prefix}{p.Name}";
    }

    private static string EmitParameterTypesArray(IMethodSymbol method)
    {
        if (method.Parameters.Length == 0) return "Type.EmptyTypes";

        var parts = method.Parameters.Select(p =>
        {
            var t = $"typeof({p.Type.ToGlobalName()})";
            if (p.RefKind is RefKind.Ref or RefKind.Out or RefKind.In)
            {
                t += ".MakeByRefType()";
            }
            return t;
        });

        return $"new[] {{ {string.Join(", ", parts)} }}";
    }

    private static string GetMethodId(IMethodSymbol method)
    {
        // stable-ish id: name + arity + parameter types
        var sig = method.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        var hash = unchecked((uint)sig.GetHashCode());
        return $"{method.Name}_{method.Parameters.Length}_{hash:X8}";
    }

    private static string GetValueTaskInnerType(ITypeSymbol valueTaskType)
    {
        if (valueTaskType is INamedTypeSymbol nts && nts.TypeArguments.Length == 1)
        {
            return nts.TypeArguments[0].ToGlobalName();
        }
        return "global::System.Object";
    }

    private static string GetTaskInnerType(ITypeSymbol taskType)
    {
        if (taskType is INamedTypeSymbol nts && nts.TypeArguments.Length == 1)
        {
            return nts.TypeArguments[0].ToGlobalName();
        }
        return "global::System.Object";
    }

    private static string EmitGenericParameterList(IMethodSymbol method)
    {
        if (!method.IsGenericMethod) return string.Empty;
        return $"<{string.Join(", ", method.TypeParameters.Select(tp => tp.Name))}>";
    }

    // When invoking the target from within the same generic method, pass through the same type parameters.
    private static string EmitGenericTypeArgumentList(IMethodSymbol method)
        => EmitGenericParameterList(method);

    private static void EmitGenericConstraints(StringBuilder sb, IMethodSymbol method, string indent)
    {
        if (!method.IsGenericMethod) return;

        // 对于 override 方法，不需要重新声明约束（约束从基方法继承）
        // 只在非 override 的泛型方法中声明约束
        // 注意：这里的 method 是 service method，如果是 class proxy 的 override 方法，
        // 我们不应该重新声明约束

        // 检查是否是 override 方法（通过检查 IsOverride 属性）
        if (method.IsOverride) return;

        foreach (var tp in method.TypeParameters)
        {
            var parts = new List<string>();
            if (tp.HasNotNullConstraint) parts.Add("notnull");
            if (tp.HasReferenceTypeConstraint) parts.Add("class");
            if (tp.HasUnmanagedTypeConstraint) parts.Add("unmanaged");
            if (tp.HasValueTypeConstraint) parts.Add("struct");

            foreach (var ct in tp.ConstraintTypes)
            {
                parts.Add(ct.ToGlobalName());
            }

            if (tp.HasConstructorConstraint) parts.Add("new()");
            if (parts.Count == 0) continue;

            sb.Append(indent)
              .Append("where ")
              .Append(tp.Name)
              .Append(" : ")
              .Append(string.Join(", ", parts))
              .AppendLine();
        }
    }
}

internal enum ReturnKindKind
{
    Void,
    Sync,
    Task,
    TaskOfT,
    ValueTask,
    ValueTaskOfT,
}

internal static class ReturnKind
{
    public static ReturnKindKind Determine(IMethodSymbol method)
    {
        if (method.ReturnsVoid) return ReturnKindKind.Void;

        var rt = method.ReturnType;
        if (rt is INamedTypeSymbol named)
        {
            if (named.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Threading.Tasks.Task")
                return ReturnKindKind.Task;
            if (named.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Threading.Tasks.Task<T>")
                return ReturnKindKind.TaskOfT;
            if (named.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Threading.Tasks.ValueTask")
                return ReturnKindKind.ValueTask;
            if (named.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Threading.Tasks.ValueTask<T>")
                return ReturnKindKind.ValueTaskOfT;
        }
        return ReturnKindKind.Sync;
    }
}
