using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace AspectCore.SourceGenerator;

internal static class RegistryEmitter
{
    public static string EmitRegistry(IReadOnlyList<ProxyEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("[assembly: global::AspectCore.DynamicProxy.AspectCoreSourceGeneratedProxyRegistryAttribute(typeof(global::AspectCore.SourceGenerated.AspectCoreSourceGeneratedProxyRegistry))]");
        sb.AppendLine();
        sb.AppendLine("namespace AspectCore.SourceGenerated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Source-generated proxy registry (auto).\n");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public sealed class AspectCoreSourceGeneratedProxyRegistry : global::AspectCore.DynamicProxy.ISourceGeneratedProxyRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        public bool TryGetProxyType(Type serviceType, Type implementationType, global::AspectCore.DynamicProxy.SourceGeneratedProxyKind kind, out Type proxyType)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (serviceType is null) throw new ArgumentNullException(nameof(serviceType));");
        sb.AppendLine("            proxyType = null;");
        sb.AppendLine();

        foreach (var e in entries)
        {
            var serviceName = e.ServiceType.ToGlobalName();
            var implName = e.ImplementationType?.ToGlobalName();
            var proxyFullName = $"global::{e.ProxyNamespace}.{e.ProxyTypeName}";
            var kindExpr = e.Kind == ProxyKind.Interface
                ? "global::AspectCore.DynamicProxy.SourceGeneratedProxyKind.Interface"
                : "global::AspectCore.DynamicProxy.SourceGeneratedProxyKind.Class";

            sb.Append("            if (kind == ").Append(kindExpr)
              .Append(" && serviceType == typeof(").Append(serviceName).Append(")");

            if (e.Kind == ProxyKind.Interface)
            {
                // For this node's type-level trigger, interface proxy is registered for implementationType==null.
                sb.Append(" && implementationType == null");
            }
            else
            {
                sb.Append(" && implementationType == typeof(").Append(implName).Append(")");
            }

            sb.AppendLine(")");
            sb.AppendLine("            {");
            sb.Append("                proxyType = typeof(").Append(proxyFullName).AppendLine(");");
            sb.AppendLine("                return true;");
            sb.AppendLine("            }");
        }

        sb.AppendLine();
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
