name: Build OSX
on: [push, pull_request]
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          6.x
          8.x
        
    - name: Build Reason
      run: "echo ref: ${{github.ref}} event: ${{github.event_name}}"
      
    - name: Build
      run: dotnet build --configuration Release AspectCore-Framework.sln
      
    - name: Run Tests
      run: dotnet test --configuration Release --no-build AspectCore-Framework.sln
